import { TarotCard } from '../types';

export const MAJOR_ARCANA: TarotCard[] = [
  {
    id: 'major_0_fool',
    name: 'The Fool',
    number: 0,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['New Beginnings', 'Innocence', 'Spontaneity', 'Free Spirit', 'Leap of Faith'],
    reversedKeywords: ['Recklessness', 'Risk-taking', 'Inconsideration', 'Hesitation', 'Naivety'],
    uprightMeaning: 'The Fool represents the dawn of a transformative journey, stepping into the unknown with pure trust in the cosmic order.',
    reversedMeaning: 'Reversed, The Fool cautions against impulsive folly or conversely, paralysis born of irrational fear of taking the first step.',
    loveMeaning: 'Spontaneous romantic beginnings, open-hearted vulnerability, and adventuring together without rigid preconceptions.',
    careerMeaning: 'Pioneering new professional ventures, uncalculated creative leaps, or embracing unconventional career paths.',
    financeMeaning: 'Carefree financial approach; suitable for modest speculative seeds but calls for basic prudence against extravagance.',
    educationMeaning: 'Approaching study with a beginner’s mind (Shoshin); open to radical new paradigms and holistic disciplines.',
    spiritualMeaning: 'The unconditioned soul (Bala-bhava) standing on the precipice of manifest existence, trusting divine grace implicitly.',
    advice: 'Take the courageous leap with childlike faith, but keep your peripheral senses alert to the physical cliff.',
    shadow: 'Willful blindness to consequences and disregard for established natural boundaries.',
    symbolism: 'The white rose of purity, the cliff edge of material reality, the faithful canine companion guarding the threshold.',
    element: 'Air',
    astrologicalAssociation: 'Uranus / The Primordial Void',
  },
  {
    id: 'major_1_magician',
    name: 'The Magician',
    number: 1,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Manifestation', 'Resourcefulness', 'Power', 'Inspired Action', 'Skill'],
    reversedKeywords: ['Illusion', 'Manipulation', 'Untapped Talents', 'Wasted Energy', 'Deception'],
    uprightMeaning: 'The Magician acts as the conscious conduit between heaven and earth, wielding the four elemental tools to manifest will into tangible reality.',
    reversedMeaning: 'Reversed, warns of misdirected ingenuity, manipulative persuasion, or procrastination masking latent creative power.',
    loveMeaning: 'Magnetism, conscious communication, and intentional courtship where desires are clearly spoken and honored.',
    careerMeaning: 'Mastery of professional craft, executive problem-solving, and synchronizing resources to launch key enterprises.',
    financeMeaning: 'Skillful resource management and the ability to turn intellectual concepts into profitable realities.',
    educationMeaning: 'Sharp analytical intellect (Buddhi), rapid mastery of complex systems, and eloquent linguistic expression.',
    spiritualMeaning: 'As above, so below (Yatha Pinde Tatha Brahmande). Conscious agency aligning individual intention with cosmic law.',
    advice: 'You possess every tool required to achieve your purpose. Channel focused intent and initiate deliberate action.',
    shadow: 'Hubristic pride believing the ego alone creates reality, severed from divine source.',
    symbolism: 'The infinity sign (Lemniscate) above the crown, the four elemental emblems on the altar, the pointing wand bridging realms.',
    element: 'Air',
    astrologicalAssociation: 'Mercury (Budha)',
  },
  {
    id: 'major_2_high_priestess',
    name: 'The High Priestess',
    number: 2,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Intuition', 'Sacred Knowledge', 'Divine Feminine', 'Subconscious', 'Mystery'],
    reversedKeywords: ['Secrets', 'Disconnection from Intuition', 'Surface Thinking', 'Repressed Feelings'],
    uprightMeaning: 'The High Priestess sits at the threshold of the unmanifest temple, guarding the intuitive wisdom and subtle tides of consciousness.',
    reversedMeaning: 'Reversed, indicates ignoring inner whispers, cognitive dissonance, or becoming swayed by external noise over inner knowing.',
    loveMeaning: 'Telepathic emotional connection, unspoken understanding, and honoring the sacred solitude within intimate bonds.',
    careerMeaning: 'Relying on strategic intuition, observing behind the scenes, and allowing projects to gestate before public disclosure.',
    financeMeaning: 'Keep financial deliberations confidential; do not reveal strategy before terms are fully matured.',
    educationMeaning: 'Deep esoteric research, contemplative scholarship, and accessing intuitive insights beyond rote memorization.',
    spiritualMeaning: 'Maya and the veil of Prakriti. The quiet receptive space where the individual soul listens to silent cosmic instruction.',
    advice: 'Withdraw from turbulent chatter; still the mental lake and heed the unforced wisdom arising from your depths.',
    shadow: 'Passive withdrawal into cold detachment or withholding vital truths out of aloofness.',
    symbolism: 'The twin pillars Boaz and Jachin, the pomegranate veil, the crescent moon resting beneath her sacred robe.',
    element: 'Water',
    astrologicalAssociation: 'Moon (Chandra)',
  },
  {
    id: 'major_3_empress',
    name: 'The Empress',
    number: 3,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Abundance', 'Fertility', 'Nurturance', 'Sensory Beauty', 'Nature'],
    reversedKeywords: ['Creative Block', 'Smothering', 'Neglect', 'Over-indulgence', 'Insecurity'],
    uprightMeaning: 'The Empress embodies lush material manifestation, organic growth, maternal grace, and sensory celebration of life.',
    reversedMeaning: 'Reversed, suggests creative depletion, emotional over-attachment, or neglect of bodily vitality.',
    loveMeaning: 'Warm, deeply affectionate romantic security, physical sensuality, and cultivating an environment of radiant comfort.',
    careerMeaning: 'Projects blossoming into tangible fruition; nurturing teams, collaborative creativity, and aesthetic design.',
    financeMeaning: 'Flourishing prosperity and natural accumulation through organic, well-nourished endeavors.',
    educationMeaning: 'Experiential, somatic learning; flourishing in supportive, aesthetically harmonious environments.',
    spiritualMeaning: 'Mahalakshmi and Jagaddhatri. The generative maternal power of nature feeding all sentient beings.',
    advice: 'Nourish your creations patiently. Celebrate the physical vessel and trust organic cycles of ripening.',
    shadow: 'Clinging possessiveness that stifles independence under the guise of loving care.',
    symbolism: 'Crown of twelve stars, the fertile wheat field, the waterfall flowing into tranquil rivers, the shield of Venus.',
    element: 'Earth',
    astrologicalAssociation: 'Venus (Shukra)',
  },
  {
    id: 'major_4_emperor',
    name: 'The Emperor',
    number: 4,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Authority', 'Structure', 'Paternal Strength', 'Order', 'Stability'],
    reversedKeywords: ['Tyranny', 'Rigidity', 'Lack of Discipline', 'Chaos', 'Abuse of Power'],
    uprightMeaning: 'The Emperor represents righteous sovereign order, protective boundaries, structured governance, and unwavering will.',
    reversedMeaning: 'Reversed, warns of authoritarian inflexibility, defensive stubbornness, or crumbling institutional structures.',
    loveMeaning: 'Stability, dependable protection, and honorable commitment where promises are backed by steadfast action.',
    careerMeaning: 'Executive leadership, structural foundation building, administrative mastery, and strategic discipline.',
    financeMeaning: 'Conservative fiscal discipline, establishing enduring institutional wealth, and sound contractual clarity.',
    educationMeaning: 'Rigorous academic discipline, structured curricula, constitutional law, and foundational logic.',
    spiritualMeaning: 'The Raja-Dharma principle. Maintaining cosmic stability through self-mastery and righteous stewardship.',
    advice: 'Establish clear boundaries and implement systematic discipline. Lead with quiet, unshakeable integrity.',
    shadow: 'Dogmatic obstinacy that crushes creative spontaneity out of fear of losing control.',
    symbolism: 'The stone throne carved with ram heads, the orb and sceptre, the armored mantle of enduring authority.',
    element: 'Fire',
    astrologicalAssociation: 'Aries (Mesha / Mars)',
  },
  {
    id: 'major_5_hierophant',
    name: 'The Hierophant',
    number: 5,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Spiritual Tradition', 'Wisdom', 'Mentorship', 'Institutions', 'Sacred Ethics'],
    reversedKeywords: ['Rebellion', 'Dogma', 'Rigid Orthodoxy', 'Unconventional Beliefs', 'Hypocrisy'],
    uprightMeaning: 'The Hierophant serves as the bridge between ancient spiritual lineage and community, transmitting sacred teachings and moral order.',
    reversedMeaning: 'Reversed, indicates outgrowing dogmatic orthodoxies, questioning spiritual hypocrisy, or seeking personalized esoteric truths.',
    loveMeaning: 'Traditional values, shared ethical commitments, spiritual alignment, and honoring sacred vows.',
    careerMeaning: 'Working within established cultural or educational institutions; seeking seasoned mentors and observing protocol.',
    financeMeaning: 'Conventional, time-tested investment models; avoiding speculative fads in favor of institutional security.',
    educationMeaning: 'Classical traditional lineage (Guru-Shishya Parampara), formal academic accreditation, and philosophical theology.',
    spiritualMeaning: 'The Guru principle (Brihaspati). Transmitting wisdom that has withstood the crucible of generations.',
    advice: 'Respect the wisdom of lineage and seasoned counsel while ensuring personal integrity remains uncompromised.',
    shadow: 'Conflating external religious rituals with genuine inner spiritual realization.',
    symbolism: 'The triple papal cross, the crossed keys of Heaven and Earth, the two acolytes receiving sacred instruction.',
    element: 'Earth',
    astrologicalAssociation: 'Taurus (Vrishabha / Jupiter-Venus nexus)',
  },
  {
    id: 'major_6_lovers',
    name: 'The Lovers',
    number: 6,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Harmony', 'Sacred Choice', 'Dual Union', 'Values Alignment', 'Attraction'],
    reversedKeywords: ['Disharmony', 'Value Conflict', 'Indecision', 'Fractured Bonds', 'Inner Disconnect'],
    uprightMeaning: 'The Lovers embodies the sacred reconciliation of dualities, moral choices guided by deep values, and reciprocal love.',
    reversedMeaning: 'Reversed, highlights inner moral conflict, conflicting obligations, or superficial attraction devoid of spiritual harmony.',
    loveMeaning: 'Soulful communion, reciprocal respect, and making mutual commitments rooted in shared life vision.',
    careerMeaning: 'High-trust partnerships, decisive crossroads requiring alignment with your deepest ethical convictions.',
    financeMeaning: 'Joint financial decisions; ensuring business partners share identical long-term values and transparency.',
    educationMeaning: 'Synthesizing conflicting disciplines (e.g. art and logic); making definitive educational specializations.',
    spiritualMeaning: 'Ardhanarishvara. The alchemical wedding of Shiva (consciousness) and Shakti (energy) within the individual heart.',
    advice: 'Make your decision from the core of your authentic values rather than momentary convenience.',
    shadow: 'Projecting your unintegrated inner shadow onto the beloved, expecting them to complete your wholeness.',
    symbolism: 'Archangel Raphael blessing the primal lovers, the Tree of Life and Tree of Knowledge, the mountain of ascension.',
    element: 'Air',
    astrologicalAssociation: 'Gemini (Mithuna)',
  },
  {
    id: 'major_7_chariot',
    name: 'The Chariot',
    number: 7,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Triumph', 'Willpower', 'Directed Drive', 'Victory', 'Overcoming Obstacles'],
    reversedKeywords: ['Loss of Control', 'Aggression', 'Directionless Energy', 'Burnout', 'Obstacles'],
    uprightMeaning: 'The Chariot represents victorious triumph achieved through disciplined mastery over conflicting instinctual drives.',
    reversedMeaning: 'Reversed, indicates reckless momentum, inner drives pulling in opposite directions, or meeting stubborn brick walls.',
    loveMeaning: 'Overcoming emotional hurdles together through shared determination, moving forward as a unified force.',
    careerMeaning: 'Decisive breakthroughs, conquering challenging targets, competitive distinction, and unstoppable career focus.',
    financeMeaning: 'Focused financial acceleration, conquering debts, and steering investments with tight operational reins.',
    educationMeaning: 'Academic stamina, conquering high-stakes examinations, and triumphing over intellectual challenges.',
    spiritualMeaning: 'The Katha Upanishad chariot metaphor: Intellect is the charioteer, the mind the reins, and the senses the horses.',
    advice: 'Harness conflicting emotions under the yoke of a single unshakeable goal. Drive forward without wavering.',
    shadow: 'Ruthless ambition that tramples empathy and sacrifices relationships to reach the podium.',
    symbolism: 'The black and white sphinxes resting in complementary stillness, the canopy of stars, the armor of resolve.',
    element: 'Water',
    astrologicalAssociation: 'Cancer (Karka)',
  },
  {
    id: 'major_8_strength',
    name: 'Strength',
    number: 8,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Courage', 'Compassion', 'Gentle Mastery', 'Inner Fortitude', 'Patience'],
    reversedKeywords: ['Self-Doubt', 'Raw Aggression', 'Weakness', 'Impatience', 'Inner Beast Out of Bounds'],
    uprightMeaning: 'Strength demonstrates the supreme power of gentle love, conscious patience, and compassionate mastery over animal instincts.',
    reversedMeaning: 'Reversed, points to inner self-doubt, reactive defensiveness, or allowing visceral fear to dictate decisions.',
    loveMeaning: 'Tender patience, loving tolerance, soothing volatile tempers through calm and unwavering acceptance.',
    careerMeaning: 'Navigating workplace politics with grace, emotional intelligence, and calm composure during turbulent negotiations.',
    financeMeaning: 'Steady, patient financial resilience; resisting panic-selling or emotional consumer impulses.',
    educationMeaning: 'Mastering difficult subjects through daily consistent effort and patience rather than cramming.',
    spiritualMeaning: 'Ahimsa and Tapas. The sublime realization that gentle spiritual presence conquers brute physical force.',
    advice: 'Master the situation not through roar and force, but through patient, fearless kindness and calm presence.',
    shadow: 'Suppressing instinctual vitality entirely until it erupts in unmanaged neurosis.',
    symbolism: 'The maiden gently holding the jaws of the golden lion, the infinity sign crown, the garland of fresh blossoms.',
    element: 'Fire',
    astrologicalAssociation: 'Leo (Simha)',
  },
  {
    id: 'major_9_hermit',
    name: 'The Hermit',
    number: 9,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Soul Searching', 'Introspection', 'Solitude', 'Inner Guidance', 'Wisdom'],
    reversedKeywords: ['Isolation', 'Loneliness', 'Withdrawal', 'Anti-Social Tendencies', 'Ignorance'],
    uprightMeaning: 'The Hermit ascends the mountain of self-realization, holding high the lantern of truth to illuminate the contemplative path.',
    reversedMeaning: 'Reversed, cautions against bitter social withdrawal, morbid isolation, or stubborn refusal to receive wise guidance.',
    loveMeaning: 'Taking space to understand your authentic needs; emotional maturity that blossoms from self-understanding.',
    careerMeaning: 'Independent analytical work, deep research, stepping back from office noise to draft long-range strategy.',
    financeMeaning: 'Prudent frugality, reviewing expenditures with an ascetic eye, seeking seasoned independent financial counsel.',
    educationMeaning: 'Solitary doctoral research, deep philosophical reading, and distilling complex data into luminous truth.',
    spiritualMeaning: 'The Muni and Vanaprastha archetype. The solitary sage whose inner light becomes a beacon for wandering souls.',
    advice: 'Step away from the crowd. In quiet contemplation, the answer you seek is already shining brightly within.',
    shadow: 'Elitist arrogance looking down on the world from an isolated spiritual ivory tower.',
    symbolism: 'The six-pointed star within the lantern, the grey cloak of humility, the staff of the pilgrim ascending the peak.',
    element: 'Earth',
    astrologicalAssociation: 'Virgo (Kanya)',
  },
  {
    id: 'major_10_wheel_of_fortune',
    name: 'Wheel of Fortune',
    number: 10,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Karmic Cycles', 'Destiny', 'Turning Point', 'Cosmic Law', 'Opportunity'],
    reversedKeywords: ['Bad Luck', 'Resistance to Change', 'Repeating Karmic Loops', 'Setbacks'],
    uprightMeaning: 'The Wheel of Fortune reveals the ceaseless cyclical revolutions of cosmic destiny, reminding us that every crest and trough is impermanent.',
    reversedMeaning: 'Reversed, suggests feeling trapped in repetitive karmic cycles or fruitlessly resisting natural tides of transformation.',
    loveMeaning: 'Fated encounters, unexpected shifts in relationship dynamics, and learning to evolve together through change.',
    careerMeaning: 'Fortuitous career breaks, unexpected elevations, and knowing when to catch the cresting wave of opportunity.',
    financeMeaning: 'Market cycles; windfall gains balancing out lean periods. Emphasizes diversifying against sudden shifts.',
    educationMeaning: 'Breakthrough opportunities in admissions or grants; synchronistic encounters that reshape academic trajectory.',
    spiritualMeaning: 'Samsara-Chakra and Kala. The divine wheel turning perpetually while the silent hub remains motionless.',
    advice: 'Anchor yourself at the serene center of the wheel. Accept the rise and fall of circumstances with poise.',
    shadow: 'Fatalistic apathy resigning personal agency under the excuse that "everything is just fate."',
    symbolism: 'The four winged creatures of the zodiac, the Hebrew letters YHVH, the descending Typhon and rising Anubis.',
    element: 'Fire',
    astrologicalAssociation: 'Jupiter (Guru)',
  },
  {
    id: 'major_11_justice',
    name: 'Justice',
    number: 11,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Cosmic Truth', 'Fairness', 'Karmic Cause and Effect', 'Clarity', 'Law'],
    reversedKeywords: ['Injustice', 'Bias', 'Dishonesty', 'Evading Responsibility', 'Unfair Blame'],
    uprightMeaning: 'Justice sits with scales and sword, measuring actions against impartial cosmic law (Dharma) with unflinching clarity.',
    reversedMeaning: 'Reversed, reveals rationalizing unethical conduct, bureaucratic bias, or suffering from unfair assessments.',
    loveMeaning: 'Equitable partnership where both parties carry equal emotional weight, radical honesty, and mutual accountability.',
    careerMeaning: 'Contractual negotiations, legal settlements, fair audits, and upholding rigorous ethical standards at work.',
    financeMeaning: 'Transparent accounting, resolving tax and debt obligations, and honest contractual dealings.',
    educationMeaning: 'Jurisprudence, analytical ethics, rigorous fact-checking, and impartial evaluation of evidence.',
    spiritualMeaning: 'Karma-Siddhanta. The exact, unbribable cosmic equilibrium where every cause generates its commensurate effect.',
    advice: 'Act with uncompromising truthfulness. Take ownership of past choices and weigh future decisions with impartiality.',
    shadow: 'Cold, merciless legalism that discards compassionate context in pursuit of rigid punishment.',
    symbolism: 'The balanced scales in the left hand, the double-edged sword of discernment held upright in the right, the purple veil.',
    element: 'Air',
    astrologicalAssociation: 'Libra (Tula)',
  },
  {
    id: 'major_12_hanged_man',
    name: 'The Hanged Man',
    number: 12,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Surrender', 'New Perspective', 'Sacred Pause', 'Letting Go', 'Metamorphosis'],
    reversedKeywords: ['Stalling', 'Useless Sacrifice', 'Martyr Complex', 'Resistance to Surrender'],
    uprightMeaning: 'The Hanged Man suspends himself willingly from the living tree, surrendering egoic control to gain profound spiritual enlightenment.',
    reversedMeaning: 'Reversed, warns of futile self-martyrdom, stubborn resistance to necessary change, or unnecessary delays.',
    loveMeaning: 'Releasing the need to control the partner; letting circumstances rest in pause to allow clarity to crystallize.',
    careerMeaning: 'Voluntary hiatus, professional realignment, stepping back to reassess core motives before initiating new projects.',
    financeMeaning: 'Financial patience; assets temporarily illiquid but accumulating subtle internal value.',
    educationMeaning: 'Shifting conceptual perspective completely; unlearning obsolete paradigms to absorb higher knowledge.',
    spiritualMeaning: 'Tapasya and Vairagya. The inversion of worldly values where egoic death gives birth to illuminated consciousness.',
    advice: 'Cease the frantic struggle. Surrender the illusion of control and view your dilemma from an inverted angle.',
    shadow: 'Indulging in a helpless victim complex, using passivity as an excuse to avoid adult responsibility.',
    symbolism: 'The halo of illumination around the serene head, the living tau-cross tree, the inverted triangular posture.',
    element: 'Water',
    astrologicalAssociation: 'Neptune / Ketu',
  },
  {
    id: 'major_13_death',
    name: 'Death',
    number: 13,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Transformation', 'Endings', 'Rebirth', 'Clearing the Old', 'Inevitable Change'],
    reversedKeywords: ['Fear of Change', 'Clinging to the Past', 'Decay', 'Stagnation', 'Resisting Metamorphosis'],
    uprightMeaning: 'Death sweeps away outworn structures to fertilize the soil for vibrant rebirth. It is the sacred gateway of radical transformation.',
    reversedMeaning: 'Reversed, signifies painful clinging to expired relationships or obsolete habits out of terrifying fear of the void.',
    loveMeaning: 'Closure of an unsustainable relationship phase, clearing emotional debris to allow genuine renewal to breathe.',
    careerMeaning: 'End of an era or job chapter; shedding an obsolete professional identity to step into an authentic vocation.',
    financeMeaning: 'Total restructuring of financial habits; cutting dead-weight liabilities to rebuild on clean ground.',
    educationMeaning: 'Graduation, concluding a major thesis, or leaving behind an outdated field of study.',
    spiritualMeaning: 'Kala and Shiva’s Mahapralaya. The dissolution of form so that consciousness may awaken into ever-newer expressions.',
    advice: 'Release what has reached its natural conclusion. Do not mourn the withered leaf when the spring shoot is waiting.',
    shadow: 'Morbid terror of physical and psychological endings leading to living a frozen, half-dead life.',
    symbolism: 'The black banner with the white mystic rose of life, the rising sun between the dual towers, the skeletal rider.',
    element: 'Water',
    astrologicalAssociation: 'Scorpio (Vrishchika)',
  },
  {
    id: 'major_14_temperance',
    name: 'Temperance',
    number: 14,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Alchemy', 'Balance', 'Moderation', 'Patience', 'Harmonious Synthesis'],
    reversedKeywords: ['Imbalance', 'Excess', 'Discord', 'Lack of Patience', 'Extremism'],
    uprightMeaning: 'Temperance blends opposing essences into a sublime divine elixir through steady patience, moderation, and alchemical grace.',
    reversedMeaning: 'Reversed, flags emotional volatility, extreme swings between excess and austerity, and hasty, uncoordinated actions.',
    loveMeaning: 'Harmonious mutual compromise, balanced emotional flow, and blending two distinct cultural or personal worlds smoothly.',
    careerMeaning: 'Mediation, cross-functional collaboration, sustainable pacing, and integrating diverse talents into a unified team.',
    financeMeaning: 'Equilibrated cash flow, steady budgeting, and avoiding financial extremes through balanced moderation.',
    educationMeaning: 'Interdisciplinary synthesis; harmonizing intuitive creativity with rigorous analytical methodology.',
    spiritualMeaning: 'Sushumna Nadi balance. The harmonious equilibrium between Ida (cooling Moon) and Pingala (solar Fire).',
    advice: 'Avoid extremes. Blend your ingredients with measured patience and allow the transformative alchemy to brew naturally.',
    shadow: 'Bland lukewarm compromise that avoids bold action under the false pretense of remaining neutral.',
    symbolism: 'The angel with one foot in water and one on land, pouring liquid continuously between dual chalices, the mountain sunrise path.',
    element: 'Fire',
    astrologicalAssociation: 'Sagittarius (Dhanu)',
  },
  {
    id: 'major_15_devil',
    name: 'The Devil',
    number: 15,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Shadow Self', 'Bondage', 'Illusion of Entrapment', 'Materialism', 'Obsession'],
    reversedKeywords: ['Liberation', 'Breaking Chains', 'Reclaiming Power', 'Overcoming Addiction'],
    uprightMeaning: 'The Devil exposes the self-imposed chains of material obsession, compulsive habits, and shadow desires masquerading as necessity.',
    reversedMeaning: 'Reversed, signals the moment of awakening, slipping free from psychological chains, and reclaiming personal sovereignty.',
    loveMeaning: 'Codependency, possessive jealousy, or intoxicating sexual magnetism that clouds ethical judgment.',
    careerMeaning: 'Golden handcuffs; feeling trapped in a toxic corporate environment solely out of prestige or material security.',
    financeMeaning: 'Over-leveraged debt, gambling or speculative greed, and allowing money anxiety to dictate soul choices.',
    educationMeaning: 'Obsessive perfectionism, intellectual arrogance, or dogmatic cynicism that ridicules higher values.',
    spiritualMeaning: 'Maya and Moha (Rahu). The seductive illusion of separateness that binds the soul to the wheel of compulsive thirst (Trishna).',
    advice: 'Examine the loose chains around your neck. You are complicit in your own entrapment; step freely into the light.',
    shadow: 'Projecting your baser desires onto others and blaming circumstances for your own lack of self-restraint.',
    symbolism: 'The goat-headed Baphomet on the altar, the loose chains around the necks of the male and female figures, the inverted pentagram.',
    element: 'Earth',
    astrologicalAssociation: 'Capricorn (Makara / Saturn-Rahu nexus)',
  },
  {
    id: 'major_16_tower',
    name: 'The Tower',
    number: 16,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Sudden Awakening', 'Shattering of Illusions', 'Crisis', 'Revelation', 'Purification'],
    reversedKeywords: ['Disaster Avoided', 'Delaying the Inevitable', 'Fear of Collapse', 'Internal Turmoil'],
    uprightMeaning: 'The lightning flash of divine truth strikes the proud tower of human illusion, shattering false security to liberate the soul.',
    reversedMeaning: 'Reversed, indicates clinging to a crumbling facade or experiencing internal emotional quakes without external collapse.',
    loveMeaning: 'A sudden confrontation that shatters illusions, exposing raw truth that forces either radical renewal or final parting.',
    careerMeaning: 'Sudden restructuring, corporate shake-ups, or collapse of an unsustainable project that frees you for authentic work.',
    financeMeaning: 'Sudden market corrections or unexpected liabilities that compel immediate financial restructuring and frugality.',
    educationMeaning: 'Demolition of a flawed theoretical hypothesis; an intellectual shock that opens radical new horizons.',
    spiritualMeaning: 'Rudra’s lightning bolt destroying the ego fortress. Sudden awakening stripping away every false identification.',
    advice: 'Do not attempt to shore up a foundation built on falsehood. Let the corrupt structure fall and embrace the liberating truth.',
    shadow: 'Addiction to chaos and drama, burning bridges recklessly instead of doing the hard work of reform.',
    symbolism: 'The lightning strike toppling the crown, the dual figures falling into the abyss, the 22 flames of divine redemption.',
    element: 'Fire',
    astrologicalAssociation: 'Mars (Mangala)',
  },
  {
    id: 'major_17_star',
    name: 'The Star',
    number: 17,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Hope', 'Inspiration', 'Divine Grace', 'Serenity', 'Healing'],
    reversedKeywords: ['Hopelessness', 'Despair', 'Disconnection', 'Pessimism', 'Lack of Faith'],
    uprightMeaning: 'The Star shines with crystalline celestial grace after the storm, offering soothing hope, intuitive inspiration, and healing.',
    reversedMeaning: 'Reversed, reflects temporary despondency, feeling spiritually unmoored, or cynicism blocking restorative healing.',
    loveMeaning: 'Open-hearted renewal, gentle emotional healing, and serene trust returning after painful vulnerability.',
    careerMeaning: 'Inspirational breakthroughs, creative vision recognized, and serving a purpose far greater than personal gain.',
    financeMeaning: 'Financial peace of mind returning; quiet optimism and sustainable, generous resource circulation.',
    educationMeaning: 'Luminous intellectual inspiration, synthesizing original creative work, and discovering your authentic calling.',
    spiritualMeaning: 'Tara and Divine Grace (Kripa). The soul pouring its cleansed waters back into the cosmic sea in selfless devotion.',
    advice: 'Have faith in the cosmic design. Let down your armored guard and allow celestial grace to restore your spirit.',
    shadow: 'Naive escapism gazing at distant stars while neglecting the practical obligations beneath your feet.',
    symbolism: 'The eight-pointed guiding star, the maiden pouring living waters onto earth and pool, the sacred ibis bird in the tree.',
    element: 'Air',
    astrologicalAssociation: 'Aquarius (Kumbha)',
  },
  {
    id: 'major_18_moon',
    name: 'The Moon',
    number: 18,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Subconscious', 'Illusions', 'Dreams', 'Shadow Realm', 'Psychic Sensitivity'],
    reversedKeywords: ['Release of Fear', 'Unveiling Deception', 'Clarity Returning', 'Overcoming Phobias'],
    uprightMeaning: 'The Moon illuminates the misty twilight path of the subconscious mind, where primal instincts, ancestral memories, and illusions dwell.',
    reversedMeaning: 'Reversed, indicates dawn breaking over nocturnal anxieties, uncovering hidden deceptions, and reclaiming grounded clarity.',
    loveMeaning: 'Unspoken emotional cross-currents, projections, heightened sensitivity, and navigating fears of emotional abandonment.',
    careerMeaning: 'Unclear office politics, hidden agendas, or relying heavily on creative dream imagery rather than spreadsheets.',
    financeMeaning: 'Deceptive contracts or ambiguous terms; do not sign agreements when numbers are veiled in mist.',
    educationMeaning: 'Psychological and mythological research, dream interpretation, and exploring the liminal frontiers of human consciousness.',
    spiritualMeaning: 'The dark night of the astral body (Chandra Mandala). Navigating the shadow realms without losing your orientation.',
    advice: 'Do not panic at nocturnal shadows. Walk the narrow path between the howling beasts with quiet, steady vigilance.',
    shadow: 'Paranoid projection allowing irrational terror to govern decisions, seeing malice where only confusion exists.',
    symbolism: 'The dog and wolf howling at the lunar disk, the crayfish emerging from the primal pool, the dual towers framing the winding path.',
    element: 'Water',
    astrologicalAssociation: 'Pisces (Meena)',
  },
  {
    id: 'major_19_sun',
    name: 'The Sun',
    number: 19,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Radiance', 'Vitality', 'Joy', 'Success', 'Enlightenment'],
    reversedKeywords: ['Temporary Cloudiness', 'Dampened Enthusiasm', 'Excessive Pride', 'Delayed Success'],
    uprightMeaning: 'The Sun blazes with life-giving clarity, sovereign vitality, joyful innocence, and triumph over all darkness.',
    reversedMeaning: 'Reversed, suggests temporary gloom obscuring radiant truth, or egotistical arrogance burning out relationships.',
    loveMeaning: 'Unfiltered warmth, playful shared joy, transparent honesty, and radiant celebratory love.',
    careerMeaning: 'High visibility, public recognition, honors, triumphant completion of projects, and sovereign creative vitality.',
    financeMeaning: 'Bountiful prosperity, clarity in assets, and warm financial confidence supporting generosity.',
    educationMeaning: 'Brilliant intellectual clarity, effortless comprehension, and graduating with high distinction.',
    spiritualMeaning: 'Surya and Gayatri. The supreme solar light of Atman illuminating the entire universe and dispelling every trace of Maya.',
    advice: 'Shine your natural light without apology. Share warmth generously and revel in the sheer joy of conscious existence.',
    shadow: 'Blinding egotism expecting the entire world to revolve around your solar presence.',
    symbolism: 'The child riding the white horse with arms outstretched, the vibrant sunflowers, the golden solar rays crowned with life.',
    element: 'Fire',
    astrologicalAssociation: 'Sun (Surya)',
  },
  {
    id: 'major_20_judgement',
    name: 'Judgement',
    number: 20,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Awakening', 'Rebirth', 'Higher Calling', 'Karmic Reckoning', 'Absolution'],
    reversedKeywords: ['Self-Doubt', 'Harsh Self-Criticism', 'Ignoring the Call', 'Guilt', 'Stalling'],
    uprightMeaning: 'The angel’s horn echoes across the valley of sleep, calling souls to rise from graves of the past into luminous spiritual resurrection.',
    reversedMeaning: 'Reversed, reflects tormenting guilt, refusing to forgive past mistakes, or pretending not to hear your destiny’s call.',
    loveMeaning: 'Forgiving past wounds completely; entering a renewed phase of transparent accountability and renewed commitment.',
    careerMeaning: 'A decisive career reckoning; stepping up to an authentic vocational calling that transcends mere salary.',
    financeMeaning: 'Reviewing past financial mistakes without self-flagellation; making radical, mature structural corrections.',
    educationMeaning: 'Synthesizing an entire lifetime of learning into a unified philosophy; presenting capstone life work.',
    spiritualMeaning: 'The final awakening (Prabodha). Transcending karmic residues to awaken into your immortal spiritual identity.',
    advice: 'Heed the inner clarion call. Forgive yourself, release the dead past, and rise joyfully into your true calling.',
    shadow: 'Sitting in self-righteous judgment of others, weaponizing moral superiority to mask your own unresolved guilt.',
    symbolism: 'Archangel Gabriel sounding the golden trumpet, figures rising joyously from floating coffins, the cross banner of redemption.',
    element: 'Fire',
    astrologicalAssociation: 'Pluto / Yama',
  },
  {
    id: 'major_21_world',
    name: 'The World',
    number: 21,
    arcana: 'major',
    suit: null,
    uprightKeywords: ['Completion', 'Integration', 'Wholeness', 'Cosmic Fulfillment', 'Mastery'],
    reversedKeywords: ['Incomplete Cycle', 'Lack of Closure', 'Shortcuts', 'Lingering Loose Ends'],
    uprightMeaning: 'The World celebrates the triumphant completion of the great soul cycle, dancing in the cosmic wreath of wholeness and liberation.',
    reversedMeaning: 'Reversed, suggests lingering near the finish line, avoiding the final closure step, or taking premature shortcuts.',
    loveMeaning: 'Harmonious completion of partnership lessons, profound unity, and celebrating a shared world of mutual fulfillment.',
    careerMeaning: 'Culmination of a major life achievement, global reach, international recognition, and fulfilling your professional magnum opus.',
    financeMeaning: 'Financial completeness and enduring security; goals achieved and wealth integrated sustainably into life.',
    educationMeaning: 'Conferral of highest degrees, international academic exchange, and holistic mastery of your chosen domain.',
    spiritualMeaning: 'Moksha and Brahman. The realization of seamless oneness where the dancer, the dance, and the cosmos are undivided.',
    advice: 'Celebrate the completion of this great cycle. Tie up final loose ends and step confidently into your expanded universe.',
    shadow: 'Refusing to close a cycle because you fear the inevitable empty space before the next journey begins.',
    symbolism: 'The dancing cosmic figure holding dual wands, the laurel wreath of victory, the four fixed signs of the zodiac at the corners.',
    element: 'Earth',
    astrologicalAssociation: 'Saturn (Shani)',
  },
];
