import { TarotCard } from '../types';

export const MINOR_WANDS: TarotCard[] = [
  {
    id: 'wands_1_ace',
    name: 'Ace of Wands',
    number: 1,
    arcana: 'minor',
    suit: 'wands',
    uprightKeywords: ['Inspiration', 'Creative Spark', 'New Venture', 'Vitality', 'Enthusiasm'],
    reversedKeywords: ['Delays', 'Lack of Passion', 'Missed Opportunity', 'Hesitation'],
    uprightMeaning: 'The primordial fire of creation bursting forth with unstoppable creative potential.',
    reversedMeaning: 'Stifled enthusiasm, creative blockages, or difficulty translating inspiration into momentum.',
    loveMeaning: 'Electrifying romantic attraction, passionate beginnings, and dynamic sexual vitality.',
    careerMeaning: 'The initial spark of a breakthrough project, entrepreneurship, or an exciting career offer.',
    financeMeaning: 'Inspiring ideas for revenue generation; an opportune moment to plant seed investments.',
    educationMeaning: 'Passionate intellectual curiosity; embarking eagerly on an inspiring course of study.',
    spiritualMeaning: 'The divine spark of Tejas igniting in the heart, awakening the will to create.',
    advice: 'Seize the creative spark immediately; act while the forge of inspiration is burning hot.',
    shadow: 'Scattered passion that burns brightly for a moment but lacks stamina to endure.',
    symbolism: 'The blooming wooden wand held by the divine hand emerging from the cloud, sprouting green leaves.',
    element: 'Fire',
    astrologicalAssociation: 'Aries, Leo, Sagittarius (Fire Triplicity)',
  },
  {
    id: 'wands_2',
    name: 'Two of Wands',
    number: 2,
    arcana: 'minor',
    suit: 'wands',
    uprightKeywords: ['Future Planning', 'Progress', 'Global Vision', 'Decisions', 'Discovery'],
    reversedKeywords: ['Fear of the Unknown', 'Lack of Planning', 'Playing Small', 'Restlessness'],
    uprightMeaning: 'Standing on the battlements holding the world in your hands, planning long-range expansion.',
    reversedMeaning: 'Paralysis by analysis, reluctance to leave comfortable borders, or poor planning.',
    loveMeaning: 'Contemplating the long-term horizon of a relationship; deciding whether to expand together.',
    careerMeaning: 'Strategic international expansion, setting long-range milestones, and stepping into leadership.',
    financeMeaning: 'Evaluating long-term asset allocation and exploring global or diversified financial options.',
    educationMeaning: 'Planning overseas study, choosing advanced specializations, and expanding intellectual horizons.',
    spiritualMeaning: 'Standing between established inner territory and the vast uncharted cosmic ocean.',
    advice: 'Look beyond immediate horizons. Plan with daring ambition while anchored in your proven foundation.',
    shadow: 'Restless discontent that fails to appreciate current achievements while obsessing over distant horizons.',
    symbolism: 'The nobleman holding a miniature globe on the castle terrace, flanked by dual rooted wands.',
    element: 'Fire',
    astrologicalAssociation: 'Mars in Aries (1st Decan)',
  },
  {
    id: 'wands_3',
    name: 'Three of Wands',
    number: 3,
    arcana: 'minor',
    suit: 'wands',
    uprightKeywords: ['Expansion', 'Foresight', 'Overseas Opportunities', 'Ships Coming In', 'Enterprise'],
    reversedKeywords: ['Obstacles to Expansion', 'Delayed Returns', 'Frustration', 'Disappointment'],
    uprightMeaning: 'Ships set sail into open waters; initial efforts begin returning tangible rewards.',
    reversedMeaning: 'Logistical bottlenecks, delayed shipments, or expectations outpacing reality.',
    loveMeaning: 'Long-distance romance thriving; planning future travels and shared growth together.',
    careerMeaning: 'Commercial trade, business operations scaling globally, and reaping fruits of early foresight.',
    financeMeaning: 'Investments beginning to yield returns; foreign markets or new revenue streams showing profit.',
    educationMeaning: 'Applying academic theories to practical global settings; international fellowships or publications.',
    spiritualMeaning: 'The soul observing the manifestation of its intentions rippling outward into the world.',
    advice: 'Maintain your expansive vantage point. Prepare the ground to receive incoming opportunities.',
    shadow: 'Impatience with natural shipping transit times, demanding immediate arrival of distant rewards.',
    symbolism: 'The merchant watching three rooted wands while golden ships navigate the calm sea.',
    element: 'Fire',
    astrologicalAssociation: 'Sun in Aries (2nd Decan)',
  },
  {
    id: 'wands_4',
    name: 'Four of Wands',
    number: 4,
    arcana: 'minor',
    suit: 'wands',
    uprightKeywords: ['Celebration', 'Homecoming', 'Harmony', 'Community', 'Milestone'],
    reversedKeywords: ['Domestic Friction', 'Delayed Celebration', 'Feeling Unwelcome', 'Transience'],
    uprightMeaning: 'A joyful milestone of stability, community celebration, and harmonious domestic peace.',
    reversedMeaning: 'Minor domestic squabbles, feeling like an outsider at celebrations, or unstable temporary living.',
    loveMeaning: 'Engagement, wedding bells, joyful domestic harmony, and celebrating shared milestones with family.',
    careerMeaning: 'Project milestone reached, corporate festivities, team camaraderie, and stable foundations.',
    financeMeaning: 'Purchasing a home, investing in family security, and celebrating financial stability.',
    educationMeaning: 'Graduation celebrations, concluding a major academic milestone with peers and mentors.',
    spiritualMeaning: 'Satsang and Grihastha-Ashrama blessing. Sacred community rejoicing in shared spiritual grace.',
    advice: 'Pause to celebrate your hard-earned milestones with those who have supported your journey.',
    shadow: 'Resting on your laurels prematurely, mistaking a base camp for the mountain summit.',
    symbolism: 'The floral bower hung between four stable wands, the celebratory youths holding fruit garlands.',
    element: 'Fire',
    astrologicalAssociation: 'Venus in Aries (3rd Decan)',
  },
  {
    id: 'wands_5',
    name: 'Five of Wands',
    number: 5,
    arcana: 'minor',
    suit: 'wands',
    uprightKeywords: ['Competition', 'Conflict', 'Rivalry', 'Clash of Egos', 'Creative Friction'],
    reversedKeywords: ['Avoiding Conflict', 'Resolution', 'Compromise', 'Exhaustion', 'Burnout'],
    uprightMeaning: 'Dynamic competition, diverse perspectives clashing, and testing ideas in the arena of action.',
    reversedMeaning: 'Fatiguing petty rivalries, resolving disputes, or burying legitimate disagreements under passive aggression.',
    loveMeaning: 'Bickering over trivialities, competing for dominance, or romantic competition for attention.',
    careerMeaning: 'Crowded market competition, brainstorming heated debates, and defending your project ideas.',
    financeMeaning: 'Financial bidding wars, competitive market pressures, and navigating conflicting financial advice.',
    educationMeaning: 'Academic debates, competitive examinations, and thriving amidst intellectual rivalry.',
    spiritualMeaning: 'The wrestling of the five senses (Indriyas) before unified spiritual mastery is attained.',
    advice: 'Engage in the sparring match with good sportsmanship. Let creative friction sharpen your blade.',
    shadow: 'Turning healthy competition into toxic egotistical warfare where winning is prioritized over truth.',
    symbolism: 'Five youths with upraised wands engaged in simulated combat without inflicting real wounds.',
    element: 'Fire',
    astrologicalAssociation: 'Saturn in Leo (1st Decan)',
  },
  {
    id: 'wands_6',
    name: 'Six of Wands',
    number: 6,
    arcana: 'minor',
    suit: 'wands',
    uprightKeywords: ['Victory', 'Public Recognition', 'Triumph', 'Acclaim', 'Confidence'],
    reversedKeywords: ['Fall from Grace', 'Ego Inflation', 'Lack of Recognition', 'Imposter Syndrome'],
    uprightMeaning: 'Triumphant public procession wearing the laurel wreath of victory and receiving acclaim.',
    reversedMeaning: 'Being snubbed for recognition, hollow victory, or excessive arrogance alienating supporters.',
    loveMeaning: 'Publicly acknowledged romance, proud mutual devotion, and celebrating partner accomplishments.',
    careerMeaning: 'Promotions, industry awards, successful product launches, and commanding respect from peers.',
    financeMeaning: 'Lucrative rewards, bonuses for outstanding performance, and public validation of investments.',
    educationMeaning: 'Academic prizes, highest test scores, scholarship honors, and public defense of thesis.',
    spiritualMeaning: 'The triumph of Dharma. When righteous action is blessed with cosmic acknowledgment.',
    advice: 'Accept legitimate praise with gracious humility. Remember those who carried you to victory.',
    shadow: 'Becoming addicted to the fleeting applause of the crowd, losing your inner moral compass.',
    symbolism: 'The rider crowned with laurel astride a caparisoned white horse, surrounded by footmen with wands.',
    element: 'Fire',
    astrologicalAssociation: 'Jupiter in Leo (2nd Decan)',
  },
  {
    id: 'wands_7',
    name: 'Seven of Wands',
    number: 7,
    arcana: 'minor',
    suit: 'wands',
    uprightKeywords: ['Defensiveness', 'Standing Your Ground', 'Courage', 'Conviction', 'Perseverance'],
    reversedKeywords: ['Giving Up', 'Overwhelmed', 'Compromised Integrity', 'Defeatism'],
    uprightMeaning: 'Standing atop the ridge defending your convictions against overwhelming odds.',
    reversedMeaning: 'Exhaustion from relentless attacks, yielding under pressure, or fighting losing battles.',
    loveMeaning: 'Defending your relationship against external disapproval or standing firm on core emotional boundaries.',
    careerMeaning: 'Holding the line against corporate competitors, defending innovative projects, and leadership resilience.',
    financeMeaning: 'Protecting your wealth from predatory lawsuits, market downturns, or aggressive debtors.',
    educationMeaning: 'Defending your dissertation or thesis against tough committee questioning with rigorous poise.',
    spiritualMeaning: 'Kshatriya-Dharma. The spiritual warrior standing steadfast against worldly delusions.',
    advice: 'Hold your high ground. You possess the positional advantage; do not compromise your core principles.',
    shadow: 'Stubborn paranoia fighting imaginary enemies and alienating genuine allies.',
    symbolism: 'The lone defender on the craggy hilltop wielding his wand with unmatched shoes, holding off six below.',
    element: 'Fire',
    astrologicalAssociation: 'Mars in Leo (3rd Decan)',
  },
  {
    id: 'wands_8',
    name: 'Eight of Wands',
    number: 8,
    arcana: 'minor',
    suit: 'wands',
    uprightKeywords: ['Swift Action', 'Rapid Travel', 'Incoming News', 'Momentum', 'Acceleration'],
    reversedKeywords: ['Delays', 'Haste Makes Waste', 'Miscommunication', 'Scattered Action'],
    uprightMeaning: 'Eight winged wands speeding unimpeded through the clear sky; events accelerating at lightning pace.',
    reversedMeaning: 'Delayed flights, missed communications, panicked haste causing careless blunders.',
    loveMeaning: 'Whirlwind romance, rapid text exchanges, spontaneous visits, and lightning-fast emotional bonding.',
    careerMeaning: 'Fast-paced projects, swift approvals, rapid market traction, and frequent business travel.',
    financeMeaning: 'Rapid cash velocity, fast-clearing transactions, and quick capital turnarounds.',
    educationMeaning: 'Accelerated learning curves, rapid absorption of materials, and quick examination turnarounds.',
    spiritualMeaning: 'Prana circulating unobstructed through the nadis; sudden spontaneous insights descending.',
    advice: 'Ride the momentum. Align your arrows clearly before release; there is no time for second-guessing.',
    shadow: 'Reckless speed that bypasses quality checks, creating collateral damage in its wake.',
    symbolism: 'Eight flying wands angling downward toward open country without human hands, bathed in sunlight.',
    element: 'Fire',
    astrologicalAssociation: 'Mercury in Sagittarius (1st Decan)',
  },
  {
    id: 'wands_9',
    name: 'Nine of Wands',
    number: 9,
    arcana: 'minor',
    suit: 'wands',
    uprightKeywords: ['Resilience', 'Grit', 'Last Stand', 'Vigilance', 'Near the Finish Line'],
    reversedKeywords: ['Exhaustion', 'Paranoia', 'Refusal to Compromise', 'Defensiveness', 'Giving In'],
    uprightMeaning: 'The wounded sentry standing firm behind his stockade, holding out for the final victory.',
    reversedMeaning: 'Chronic exhaustion, hyper-vigilance leading to burnout, or projecting past wounds onto safe terrain.',
    loveMeaning: 'Guarded heart from past heartbreaks; needing patience to rebuild trust with a worthy partner.',
    careerMeaning: 'Final sprint of an exhausting project; staying vigilant through the final compliance audit.',
    financeMeaning: 'Guarding reserves through the final stretch of an economic downturn; holding the line.',
    educationMeaning: 'Final week before doctoral submission or bar exams; pushed to the limit but persevering.',
    spiritualMeaning: 'Enduring the final subtle tests of the ego before dawn breaks on spiritual awakening.',
    advice: 'Do not drop your guard now. You have endured too much to yield in the final stretch. Hold on.',
    shadow: 'Chronic defensive hostility that assumes everyone is an enemy trying to breach your walls.',
    symbolism: 'The bandaged warrior leaning upon his staff, backed by eight upright wands forming a defensive palisade.',
    element: 'Fire',
    astrologicalAssociation: 'Moon in Sagittarius (2nd Decan)',
  },
  {
    id: 'wands_10',
    name: 'Ten of Wands',
    number: 10,
    arcana: 'minor',
    suit: 'wands',
    uprightKeywords: ['Burden', 'Overload', 'Responsibility', 'Carrying Too Much', 'Culmination'],
    reversedKeywords: ['Delegation', 'Collapsing Under Weight', 'Releasing Burdens', 'Refusal to Delegate'],
    uprightMeaning: 'Carrying a heavy bundle of ten wands toward the city gates; the weight of success.',
    reversedMeaning: 'Crushing burnout, dropping the load, or finally learning the wisdom of delegation.',
    loveMeaning: 'Carrying all emotional labor in the partnership alone; exhaustion demanding honest division of duties.',
    careerMeaning: 'Overwhelmed by excessive responsibilities, micro-management, or inability to say no to more work.',
    financeMeaning: 'Overextended financial commitments, heavy mortgages, or carrying the debt load of others.',
    educationMeaning: 'Overloaded academic schedule, cramming too many courses, and mental exhaustion.',
    spiritualMeaning: 'Carrying unnecessary karmic baggage that does not belong to your authentic soul path.',
    advice: 'Put down what is not yours to carry. Delegate responsibilities before your spine buckles.',
    shadow: 'Pride in suffering, wearing exhaustion as a badge of honor to prove your indispensability.',
    symbolism: 'The laborer bent under the weight of ten heavy wands, trudging toward the distant city rooftops.',
    element: 'Fire',
    astrologicalAssociation: 'Saturn in Sagittarius (3rd Decan)',
  },
  {
    id: 'wands_page',
    name: 'Page of Wands',
    number: 11,
    arcana: 'minor',
    suit: 'wands',
    uprightKeywords: ['Enthusiastic Messenger', 'Creative Curiosity', 'Spunk', 'Exploration', 'Good News'],
    reversedKeywords: ['Immaturity', 'Procrastination', 'Unreliable', 'False Starts', 'Temper Tantrums'],
    uprightMeaning: 'The spirited young messenger gazing intently at his budding staff, full of creative zest.',
    reversedMeaning: 'Childish petulance, loud ideas with zero execution follow-through, or discouraging gossip.',
    loveMeaning: 'Playful flirtation, lighthearted romantic messages, and eager spontaneous dates.',
    careerMeaning: 'Internship enthusiasm, fresh creative briefs, and an eagerness to learn on the job.',
    financeMeaning: 'Small but exciting financial prospects; exploring new side hustles with enthusiasm.',
    educationMeaning: 'Keen curiosity in class, active participation, and exploring novel educational hobbies.',
    spiritualMeaning: 'The fresh, curious seeker eager to explore spiritual scriptures with childlike wonder.',
    advice: 'Embrace your creative curiosity. Deliver your message boldly and experiment without fear of error.',
    shadow: 'All talk and no action; starting ten projects with fiery passion and abandoning all ten next week.',
    symbolism: 'The feathered youth gazing at his sprouting staff in a desert landscape with Egyptian salamander robes.',
    element: 'Fire',
    astrologicalAssociation: 'Earth of Fire',
  },
  {
    id: 'wands_knight',
    name: 'Knight of Wands',
    number: 12,
    arcana: 'minor',
    suit: 'wands',
    uprightKeywords: ['Action-Oriented', 'Adventurous', 'Passionate Drive', 'Impulsive', 'Charismatic'],
    reversedKeywords: ['Recklessness', 'Short Temper', 'Volatile', 'Burnout', 'Scattered Focus'],
    uprightMeaning: 'The armored knight charging across the desert on his fiery steed, driven by bold passion.',
    reversedMeaning: 'Arrogant bravado, impulsive gambles that backfire, and abandoning projects mid-charge.',
    loveMeaning: 'Passionate whirlwind courtship, intoxicating chemistry, but requires grounding to ensure longevity.',
    careerMeaning: 'Aggressive sales drives, pioneering field operations, and leading high-energy launches.',
    financeMeaning: 'Speculative investments, fast-moving financial deals, and daring entrepreneurial risks.',
    educationMeaning: 'Audacious debate performance, defending controversial theses, and thriving under pressure.',
    spiritualMeaning: 'The ardent spiritual adventurer journeying fearlessly through inner trials.',
    advice: 'Charge forward with your passion, but ensure your horse does not throw you over the precipice.',
    shadow: 'Inability to stay still, burning through people and opportunities out of addiction to adrenaline.',
    symbolism: 'The knight in armor with fire-tipped plumes on a rearing chestnut stallion against desert peaks.',
    element: 'Fire',
    astrologicalAssociation: 'Air of Fire',
  },
  {
    id: 'wands_queen',
    name: 'Queen of Wands',
    number: 13,
    arcana: 'minor',
    suit: 'wands',
    uprightKeywords: ['Confidence', 'Warmth', 'Radiant Magnetism', 'Fierce Independence', 'Creativity'],
    reversedKeywords: ['Jealousy', 'Insecurity', 'Domineering', 'Demanding Attention', 'Vengeful'],
    uprightMeaning: 'The radiant queen seated on her throne holding a sunflower and black cat, exuding warm authority.',
    reversedMeaning: 'Insecure theatricality, petty catty jealousy, or smothering others with demanding drama.',
    loveMeaning: 'Warm, intensely loyal, radiant romantic partner who loves with fierce authenticity and humor.',
    careerMeaning: 'Charismatic leadership, creative director, motivating teams through inspiring personal confidence.',
    financeMeaning: 'Confident financial autonomy, generous hospitality, and investing in creative ventures.',
    educationMeaning: 'Inspiring mentorship, leading academic societies with vibrant charisma and warmth.',
    spiritualMeaning: 'The fully realized solar feminine; radiant Shakti shining without diminishing others.',
    advice: 'Step into your radiant authority. Own your space with warm confidence, humor, and grace.',
    shadow: 'Demanding constant applause and taking offense at the slightest perceived lack of adoration.',
    symbolism: 'The sunflower in her left hand, the black cat of intuition at her feet, the lion-carved throne.',
    element: 'Fire',
    astrologicalAssociation: 'Water of Fire',
  },
  {
    id: 'wands_king',
    name: 'King of Wands',
    number: 14,
    arcana: 'minor',
    suit: 'wands',
    uprightKeywords: ['Visionary Leader', 'Inspiration', 'Bold Entrepreneurship', 'Charisma', 'Honor'],
    reversedKeywords: ['Autocratic', 'Overbearing', 'Unrealistic Expectations', 'Impulsive Ego'],
    uprightMeaning: 'The sovereign master of fire seated upon his lion throne, directing vast visionary enterprises.',
    reversedMeaning: 'Authoritarian bully, making grand unworkable demands, or hubris leading to public fall.',
    loveMeaning: 'Devoted, noble, protective romantic partner who inspires mutual greatness and loyalty.',
    careerMeaning: 'Visionary CEO, senior enterprise leader, inspiring entire organizations through visionary drive.',
    financeMeaning: 'Bold corporate financing, visionary investments that create new markets, and generous stewardship.',
    educationMeaning: 'Leading dean or academic visionary founding new institutes and inspiring generations of scholars.',
    spiritualMeaning: 'The Raja-Rishi. The spiritual ruler who channels divine creative will into righteous worldly manifestation.',
    advice: 'Lead from the front. Inspire your team through your visionary conviction and noble magnanimity.',
    shadow: 'Believing your vision is the only reality, scorning practical logistics and constructive criticism.',
    symbolism: 'The crowned king in robes decorated with lions and salamanders, holding a living budding staff.',
    element: 'Fire',
    astrologicalAssociation: 'Fire of Fire',
  },
];
