import { TarotCard } from '../types';

export const MINOR_SWORDS: TarotCard[] = [
  {
    id: 'swords_1_ace',
    name: 'Ace of Swords',
    number: 1,
    arcana: 'minor',
    suit: 'swords',
    uprightKeywords: ['Mental Clarity', 'Breakthrough', 'Unvarnished Truth', 'Sharp Intellect', 'Justice'],
    reversedKeywords: ['Clouded Judgment', 'Brutal Words', 'Miscommunication', 'Hostility', 'Cynicism'],
    uprightMeaning: 'The upright double-edged sword crowned with laurel, slicing cleanly through illusion to reveal naked truth.',
    reversedMeaning: 'Cruel sarcasm, intellectual arrogance, clouded perception, or using truth as a weapon to wound others.',
    loveMeaning: 'Radical honesty in communication, cutting through illusions, and reaching crystal-clear relationship decisions.',
    careerMeaning: 'Intellectual breakthrough, formulating decisive strategy, winning legal cases, and rigorous analytical clarity.',
    financeMeaning: 'Transparent financial auditing, cutting unnecessary overhead, and making rational, unsentimental money decisions.',
    educationMeaning: 'Exceptional intellectual acumen, mastering formal logic, scientific methodology, and rigorous analytical thinking.',
    spiritualMeaning: 'The sword of Viveka (Discrimination). Severing the knot of ignorance (Avidya) to reveal pristine consciousness.',
    advice: 'Cut through the fog with uncompromising clarity. Speak the truth, but temper your blade with wisdom.',
    shadow: 'Cold, surgical cruelty that uses intellectual superiority to humiliate and destroy rather than liberate.',
    symbolism: 'The divine hand holding aloft the double-edged sword through a golden crown adorned with olive and palm branches.',
    element: 'Air',
    astrologicalAssociation: 'Gemini, Libra, Aquarius (Air Triplicity)',
  },
  {
    id: 'swords_2',
    name: 'Two of Swords',
    number: 2,
    arcana: 'minor',
    suit: 'swords',
    uprightKeywords: ['Stalemate', 'Difficult Choice', 'Blindfolded Neutrality', 'Truce', 'Blocked Emotions'],
    reversedKeywords: ['Decision Made', 'Information Overload', 'Lifting the Blindfold', 'Truth Revealed'],
    uprightMeaning: 'A blindfolded figure seated before the sea with two crossed swords, balancing conflicting thoughts in quiet truce.',
    reversedMeaning: 'The blindfold falls away; forced to make an inevitable decision amidst overwhelming external noise.',
    loveMeaning: 'Refusing to face a painful truth about a relationship; emotional stalemate and avoiding difficult talks.',
    careerMeaning: 'Deadlock in negotiations, being caught between conflicting factions, or delaying an urgent executive decision.',
    financeMeaning: 'Postponing financial choices out of fear of making a mistake; freezing investments in neutral accounts.',
    educationMeaning: 'Balancing two equally compelling hypotheses; struggling to choose between two academic concentrations.',
    spiritualMeaning: 'Holding the mind in absolute stillness amidst opposing polarities (Dvandvas) before taking action.',
    advice: 'Remove the blindfold. You cannot avoid this choice forever; look at the facts and decide with courage.',
    shadow: 'Willful ignorance pretending a crisis does not exist to preserve a fragile, suffocating peace.',
    symbolism: 'The blindfolded woman seated on a stone bench holding two crossed swords over her chest before a nocturnal sea.',
    element: 'Air',
    astrologicalAssociation: 'Moon in Libra (1st Decan)',
  },
  {
    id: 'swords_3',
    name: 'Three of Swords',
    number: 3,
    arcana: 'minor',
    suit: 'swords',
    uprightKeywords: ['Heartbreak', 'Sorrow', 'Painful Truth', 'Betrayal', 'Emotional Release'],
    reversedKeywords: ['Healing', 'Forgiveness', 'Releasing Pain', 'Overcoming Grief', 'Optimism'],
    uprightMeaning: 'A red heart pierced by three swords beneath storm clouds and driving rain; the sorrow of surgical truth.',
    reversedMeaning: 'The storm clouds beginning to break, pulling out the swords, forgiving past betrayals, and healing.',
    loveMeaning: 'Heartbreak, painful breakup, discovery of deceit, or having romantic illusions shattered by reality.',
    careerMeaning: 'Painful job termination, breach of contract, or painful constructive criticism that stings deeply.',
    financeMeaning: 'Devastating financial loss or unexpected contractual betrayal requiring emotional resilience.',
    educationMeaning: 'Failing an important examination or having a cherished research paper harshly rejected by peers.',
    spiritualMeaning: 'The purification of the heart through sorrow. Pain stripping away superficial ego attachments.',
    advice: 'Allow yourself to feel the grief fully without suppression. The heart that breaks open becomes vast enough to heal.',
    shadow: 'Indulging in bitter victimhood, nourishing resentment and nursing old grievances like prized possessions.',
    symbolism: 'A vibrant red heart pierced through by three silver swords hanging suspended against grey rain clouds.',
    element: 'Air',
    astrologicalAssociation: 'Saturn in Libra (2nd Decan)',
  },
  {
    id: 'swords_4',
    name: 'Four of Swords',
    number: 4,
    arcana: 'minor',
    suit: 'swords',
    uprightKeywords: ['Rest', 'Recuperation', 'Contemplation', 'Sanctuary', 'Mental Recovery'],
    reversedKeywords: ['Burnout', 'Restlessness', 'Premature Return', 'Exhaustion', 'Forced Retreat'],
    uprightMeaning: 'The sculpted knight lying in repose upon his tomb with hands in prayer beneath three swords, taking sacred rest.',
    reversedMeaning: 'Ignoring signs of mental exhaustion, returning to battle prematurely, or awakening refreshed from retreat.',
    loveMeaning: 'Taking a necessary emotional pause from dating or relationship conflict to recharge and regain perspective.',
    careerMeaning: 'Taking medical leave, scheduled sabbatical, or stepping away from office turmoil to restore mental stamina.',
    financeMeaning: 'Pausing major purchases or investments; consolidating assets and avoiding impulsive expenditures.',
    educationMeaning: 'Taking a study break to prevent cognitive overload; resting the brain to allow concepts to integrate.',
    spiritualMeaning: 'Pratyahara and Dhyana. Withdrawing the senses from external combat into the quiet sanctuary of the soul.',
    advice: 'Lay down your sword. Rest is not a waste of time; it is a sacred necessity for tactical victory tomorrow.',
    shadow: 'Escapist paralysis; staying in retreat indefinitely to hide from the legitimate demands of life.',
    symbolism: 'The knight’s effigy resting in prayer upon a tomb, three swords mounted above on the wall, one beneath him.',
    element: 'Air',
    astrologicalAssociation: 'Jupiter in Libra (3rd Decan)',
  },
  {
    id: 'swords_5',
    name: 'Five of Swords',
    number: 5,
    arcana: 'minor',
    suit: 'swords',
    uprightKeywords: ['Pyrrhic Victory', 'Ego Clash', 'Defeat', 'Unethical Triumph', 'Bitterness'],
    reversedKeywords: ['Reconciliation', 'Making Amends', 'Walking Away from Drama', 'Burying the Hatchet'],
    uprightMeaning: 'A smirking victor gathering the dropped swords of his vanquished foes under ragged storm clouds; winning at too high a cost.',
    reversedMeaning: 'Releasing the desperate need to be right, apologizing for past cruelty, and walking away from toxic arguments.',
    loveMeaning: 'Scoring cheap points in arguments, winning the debate but destroying the relationship’s warmth and trust.',
    careerMeaning: 'Cutthroat corporate backstabbing, hostile office politics, and toxic rivalries that damage everyone involved.',
    financeMeaning: 'Unethical business practices, cheating on contracts, or suffering financial defeat from a ruthless competitor.',
    educationMeaning: 'Academic plagiarism, sabotaging classmates, or aggressive debate tactics that win rounds but lose friends.',
    spiritualMeaning: 'The folly of the Asuric ego. Winning the worldly argument while inflicting mortal wounds on your own soul.',
    advice: 'Pick your battles wisely. Ask yourself: do you want to be right, or do you want to be in peace and harmony?',
    shadow: 'Taking malicious pleasure in the humiliation of others, gloating over fallen rivals.',
    symbolism: 'The smirking youth clutching three swords looking back at two weeping figures walking toward the stormy sea.',
    element: 'Air',
    astrologicalAssociation: 'Venus in Aquarius (1st Decan)',
  },
  {
    id: 'swords_6',
    name: 'Six of Swords',
    number: 6,
    arcana: 'minor',
    suit: 'swords',
    uprightKeywords: ['Transition', 'Moving to Calm Waters', 'Leaving Trouble Behind', 'Healing Journey', 'Passage'],
    reversedKeywords: ['Stuck in Turmoil', 'Emotional Baggage', 'Resisting Transition', 'Unresolved Past'],
    uprightMeaning: 'A ferryman silently steering his boat carrying a mother and child across rough waters toward a peaceful shore.',
    reversedMeaning: 'Dragging old trauma into new territory, canceled travel plans, or inability to let go of a toxic past.',
    loveMeaning: 'Moving forward together after a storm, leaving behind toxicity, and embarking on a gentle path of healing.',
    careerMeaning: 'Relocating for work, leaving a hostile department, and transitioning to a calmer, more productive work environment.',
    financeMeaning: 'Gradually recovering from financial distress; settling debts and moving toward fiscal equilibrium.',
    educationMeaning: 'Transferring to a supportive institution; moving from chaotic academic stress into focused research.',
    spiritualMeaning: 'The soul being ferry-manned across the river of sorrow (Dukha) toward the shores of equanimity.',
    advice: 'Keep your eyes on the peaceful shore ahead. The water was rough, but calm horizons are now within reach.',
    shadow: 'Carrying the heavy swords of old bitterness in the boat, risking sinking the vessel in the new harbor.',
    symbolism: 'The boat carrying cloaked passengers and six upright swords, moving from rippling water to serene glass.',
    element: 'Air',
    astrologicalAssociation: 'Mercury in Aquarius (2nd Decan)',
  },
  {
    id: 'swords_7',
    name: 'Seven of Swords',
    number: 7,
    arcana: 'minor',
    suit: 'swords',
    uprightKeywords: ['Strategy', 'Stealth', 'Tactical Cunning', 'Deception', 'Solo Operation'],
    reversedKeywords: ['Confession', 'Caught Red-Handed', 'Coming Clean', 'Failed Scheme', 'Conscience Waking'],
    uprightMeaning: 'A stealthy figure tiptoeing away from an enemy camp carrying five swords while glancing nervously over his shoulder.',
    reversedMeaning: 'Secrets exposed, conscience compelling a full confession, or realizing that deception cannot sustain long-term success.',
    loveMeaning: 'Secrecy in relationships, emotional dishonesty, hiding texts, or strategic self-protection out of fear.',
    careerMeaning: 'Proprietary corporate strategy, covert maneuvering, intellectual property theft, or navigating workplace politics.',
    financeMeaning: 'Hidden financial clauses, tax evasions, or needing to protect your assets with discreet tactical privacy.',
    educationMeaning: 'Academic cheating, cutting corners in research, or using unconventional shortcuts to bypass requirements.',
    spiritualMeaning: 'The trickster intellect trying to outsmart cosmic law, only to realize that every deed is witnessed by the Self.',
    advice: 'If strategic diplomacy is required, proceed with tactical precision. But ensure you do not violate your core integrity.',
    shadow: 'Pathological deception and cowardice, sneaking away from consequences and betraying those who trust you.',
    symbolism: 'The man tiptoeing on tiptoe carrying five swords in his arms, leaving two planted in the military tent camp.',
    element: 'Air',
    astrologicalAssociation: 'Moon in Aquarius (3rd Decan)',
  },
  {
    id: 'swords_8',
    name: 'Eight of Swords',
    number: 8,
    arcana: 'minor',
    suit: 'swords',
    uprightKeywords: ['Self-Imposed Traps', 'Limiting Beliefs', 'Victim Mentality', 'Mental Prison', 'Isolation'],
    reversedKeywords: ['Liberation', 'Opening Your Eyes', 'Stepping Out of the Trap', 'Reclaiming Power'],
    uprightMeaning: 'A blindfolded, loosely bound maiden standing trapped in mud, encircled by eight swords with the open castle path behind.',
    reversedMeaning: 'Realizing the ropes are loose, removing the blindfold, and stepping out of the imaginary prison of self-doubt.',
    loveMeaning: 'Feeling trapped in a relationship by your own fears, believing you have no options when the door is unlocked.',
    careerMeaning: 'Feeling stuck in a dead-end job due to fear of the job market; paralysis caused by limiting beliefs.',
    financeMeaning: 'Paralyzing debt anxiety making you avoid looking at bank balances; feeling helpless when simple actions exist.',
    educationMeaning: 'Imposter syndrome, test paralysis, and convincing yourself that you are incapable of mastering the material.',
    spiritualMeaning: 'Maya’s greatest illusion: the soul believing it is bound when in truth it is eternally free and unchained.',
    advice: 'Examine your perceived cage. The ropes are loose and the swords do not touch you; simply step forward and walk free.',
    shadow: 'Addiction to helplessness, waiting for an external savior so you never have to take responsibility for your life.',
    symbolism: 'The woman bound in red cords with a white blindfold, surrounded by eight swords in marshy ground with a castle behind.',
    element: 'Air',
    astrologicalAssociation: 'Jupiter in Gemini (1st Decan)',
  },
  {
    id: 'swords_9',
    name: 'Nine of Swords',
    number: 9,
    arcana: 'minor',
    suit: 'swords',
    uprightKeywords: ['Anxiety', 'Nightmares', 'Insomnia', 'Mental Anguish', 'Catastrophizing'],
    reversedKeywords: ['Dawn After Darkness', 'Releasing Guilt', 'Seeking Help', 'Healing Anxiety', 'Reality Check'],
    uprightMeaning: 'A weeping figure sitting up in bed with head in hands beneath nine black swords mounted on the wall; the nightmare of anxiety.',
    reversedMeaning: 'Recognizing that your worst fears were projections, the morning light dispelling terror, and seeking therapy.',
    loveMeaning: 'Tormenting worries about partner fidelity, sleepless nights over imagined breakups, and runaway anxieties.',
    careerMeaning: 'Severe work stress, fear of professional failure, and catastrophizing minor mistakes into career catastrophe.',
    financeMeaning: 'Late-night financial panic, obsessive fear of poverty, and overwhelming anxiety over numbers.',
    educationMeaning: 'Exam anxiety, academic panic attacks, and mental anguish caused by impossible perfectionism.',
    spiritualMeaning: 'The torment of the unmastered mind (Chitta Vritti). Suffering from projections that have no objective reality.',
    advice: 'Turn on the light. The swords are hanging on the wall; none have pierced your flesh. Breathe and ground yourself in the present.',
    shadow: 'Nourishing catastrophic fantasies until you induce the very crisis you dreaded.',
    symbolism: 'The figure weeping into hands on a carved wooden bed with a quilt of astrological roses, nine swords on the black wall.',
    element: 'Air',
    astrologicalAssociation: 'Mars in Gemini (2nd Decan)',
  },
  {
    id: 'swords_10',
    name: 'Ten of Swords',
    number: 10,
    arcana: 'minor',
    suit: 'swords',
    uprightKeywords: ['Rock Bottom', 'Painful Ending', 'Backstabbing', 'Dawn of Renewal', 'Defeat'],
    reversedKeywords: ['Recovery', 'Surviving the Worst', 'Rising from the Ashes', 'Resurrection', 'Healing'],
    uprightMeaning: 'A figure pinned to the earth by ten swords under black skies, but a golden dawn breaks on the distant horizon; rock bottom reached.',
    reversedMeaning: 'The worst is over; beginning the slow, steady journey of recovery and rising from the ashes of disaster.',
    loveMeaning: 'The absolute, definitive end of a toxic relationship; no more wounds can be inflicted; the final curtain has fallen.',
    careerMeaning: 'Complete project termination, sudden redundancy, or total failure of a strategy; clearing the field for a fresh start.',
    financeMeaning: 'Reaching financial rock bottom, declared bankruptcy, and the unexpected relief that comes with starting from zero.',
    educationMeaning: 'Total academic burnout or failing a final attempt; realizing your true path lies in an entirely different direction.',
    spiritualMeaning: 'The complete annihilation of egoic illusions. The darkest hour of the night that directly precedes the sunrise.',
    advice: 'Accept that this cycle is completely over. Do not fight the ending; the worst has happened, and from here, you can only rise.',
    shadow: 'Melodramatic martyrdom; wallowing theatrically in defeat to elicit pity from spectators.',
    symbolism: 'The prone figure pinned by ten swords wrapped in a crimson cloak, the black storm sky lifting to reveal golden dawn over the sea.',
    element: 'Air',
    astrologicalAssociation: 'Sun in Gemini (3rd Decan)',
  },
  {
    id: 'swords_page',
    name: 'Page of Swords',
    number: 11,
    arcana: 'minor',
    suit: 'swords',
    uprightKeywords: ['Curious Mind', 'Vigilance', 'Mental Agility', 'Truth-Seeker', 'Sprightly Intellect'],
    reversedKeywords: ['Deceitful Gossip', 'Paranoia', 'All Talk No Substance', 'Cynical Sniping', 'Spying'],
    uprightMeaning: 'An alert, sprightly youth standing on windswept terrain with sword held high, scanning the horizon with vigilant curiosity.',
    reversedMeaning: 'Spreading vicious internet rumors, cyber-stalking, defensive argumentative behavior, or paranoid suspicion.',
    loveMeaning: 'Inquisitive courtship, stimulating intellectual banter, asking probing questions, and seeking absolute honesty.',
    careerMeaning: 'Fact-checking, investigative journalism, legal research, data analysis, and sharp analytical vigilance.',
    financeMeaning: 'Auditing statements carefully, scrutinizing fine print, and asking tough questions before signing contracts.',
    educationMeaning: 'Sharp critical thinking, debate skills, investigative curiosity, and challenging orthodox theories.',
    spiritualMeaning: 'The awakened intellect (Buddhi) slicing through sentimental superstition with sharp discrimination.',
    advice: 'Keep your intellect sharp and your senses vigilant. Ask penetrating questions and demand verifiable truth.',
    shadow: 'Using your sharp tongue and intellectual cleverness to belittle others and assert superiority.',
    symbolism: 'The athletic youth holding a sword with both hands on a windy hill with billowing clouds and flying birds.',
    element: 'Air',
    astrologicalAssociation: 'Earth of Air',
  },
  {
    id: 'swords_knight',
    name: 'Knight of Swords',
    number: 12,
    arcana: 'minor',
    suit: 'swords',
    uprightKeywords: ['Fast-Thinking', 'Direct Action', 'Intellectual Ambition', 'Unyielding Drive', 'Sharp Focus'],
    reversedKeywords: ['Reckless Aggression', 'Tactless Blunders', 'Brutal Sarcasm', 'Burnout', 'Blind Charging'],
    uprightMeaning: 'The armored knight charging at furious speed on his galloping steed with sword unsheathed, driven by fierce intellectual conviction.',
    reversedMeaning: 'Rushing in with arrogant recklessness, cutting people down with cruel words, or crashing blindly into obstacles.',
    loveMeaning: 'Intense, fast-moving courtship; intellectually stimulating but can be emotionally abrasive without warmth.',
    careerMeaning: 'High-speed problem solving, crisis management, decisive corporate takeovers, and cutting through bureaucracy.',
    financeMeaning: 'Decisive, aggressive market moves; capitalizing swiftly on fast-closing arbitrage opportunities.',
    educationMeaning: 'Blazing through academic research, delivering fiercely argued debate rebuttals, and publishing boldly.',
    spiritualMeaning: 'The relentless warrior of truth who charges fearlessly into the citadel of delusion to liberate understanding.',
    advice: 'Charge forward with your intellectual vision, but check your blind spots and temper your directness with basic kindness.',
    shadow: 'Steamrolling others in debate, caring more about proving yourself right than discovering the actual truth.',
    symbolism: 'The knight in armor riding a white stallion at full gallop against gale-force winds and serrated storm clouds.',
    element: 'Air',
    astrologicalAssociation: 'Air of Air',
  },
  {
    id: 'swords_queen',
    name: 'Queen of Swords',
    number: 13,
    arcana: 'minor',
    suit: 'swords',
    uprightKeywords: ['Clear Boundaries', 'Perceptive Wisdom', 'Unbiased Truth', 'Independence', 'Direct Speech'],
    reversedKeywords: ['Coldness', 'Bitterness', 'Hyper-Critical', 'Cruel Tongue', 'Emotional Armor'],
    uprightMeaning: 'The sovereign queen seated upon her stone throne in the clouds, extending one hand in invitation while holding the sword of truth upright.',
    reversedMeaning: 'Ice-cold cruelty, weaponized sarcasm, emotional armor that rejects all warmth, or nursing ancient bitterness.',
    loveMeaning: 'Clear, mature communication; high standards, valuing emotional honesty over sweet flatteries, and strong boundaries.',
    careerMeaning: 'Senior editor, judge, executive strategist, cutting through corporate spin to deliver objective assessments.',
    financeMeaning: 'Surgical financial discipline, zero sentimentality in business contracts, and meticulous accounting.',
    educationMeaning: 'Distinguished critical theorist, uncompromising academic peer reviewer, and master of logical clarity.',
    spiritualMeaning: 'Prajna (Transcendent Wisdom). The mind stripped of sentimental attachment, resting in radiant, impartial clarity.',
    advice: 'Speak the truth clearly and establish firm boundaries. You can be completely honest without being cruel.',
    shadow: 'Refusing to let anyone touch your heart, using your razor-sharp intellect as a shield against intimacy.',
    symbolism: 'The queen in profile holding the sword upright in her right hand, her left hand extended, butterflies carved on her throne.',
    element: 'Air',
    astrologicalAssociation: 'Water of Air',
  },
  {
    id: 'swords_king',
    name: 'King of Swords',
    number: 14,
    arcana: 'minor',
    suit: 'swords',
    uprightKeywords: ['Intellectual Authority', 'Mastery of Truth', 'Impartial Judgment', 'Strategic Vision', 'Discipline'],
    reversedKeywords: ['Tyrant', 'Manipulative Logic', 'Cold Brutality', 'Abuse of Power', 'Dogmatic Dogmatism'],
    uprightMeaning: 'The sovereign judge seated upon his marble throne holding the naked blade of justice, commanding total intellectual mastery.',
    reversedMeaning: 'A cold, ruthless authoritarian using legalistic sophistry to oppress, manipulate, and crush dissent.',
    loveMeaning: 'Principled, intellectually mature partner who communicates with utter clarity, integrity, and rational honor.',
    careerMeaning: 'Chief legal counsel, senior judge, high-stakes military or corporate strategist, and final arbiter of decisions.',
    financeMeaning: 'Impartial, highly rational fiscal governance; adhering strictly to legal compliance and sound strategy.',
    educationMeaning: 'Supreme intellectual authority, chancellor, master philosopher, and guardian of rigorous scientific truth.',
    spiritualMeaning: 'The Dharmaraja (Lord of Righteous Law). The fully integrated rational mind serving cosmic truth without bias.',
    advice: 'Decide with impartial justice and rational clarity. Let truth, facts, and ethical principles guide your verdict.',
    shadow: 'Divorcing intellect from the human heart completely, treating living human beings as mere chess pieces.',
    symbolism: 'The crowned king seated squarely facing forward with the sword upright, purple mantle over armor, two birds flying in the sky.',
    element: 'Air',
    astrologicalAssociation: 'Fire of Air',
  },
];
