import { TarotCard } from '../types';

export const MINOR_CUPS: TarotCard[] = [
  {
    id: 'cups_1_ace',
    name: 'Ace of Cups',
    number: 1,
    arcana: 'minor',
    suit: 'cups',
    uprightKeywords: ['Unconditional Love', 'Emotional Awakening', 'Compassion', 'Spiritual Grace', 'Intimacy'],
    reversedKeywords: ['Emotional Drain', 'Blocked Feelings', 'Self-Doubt', 'Wasted Affection'],
    uprightMeaning: 'The celestial chalice overflowing with five streams of living water, offering boundless love and spiritual peace.',
    reversedMeaning: 'Emotional exhaustion, withholding vulnerable feelings, or feeling unloved due to closed inner gates.',
    loveMeaning: 'Deep spiritual love awakening, soulmate connection, emotional vulnerability, and heart-opening romance.',
    careerMeaning: 'Fulfilling humanitarian vocation, artistic inspiration, and harmonious relationships with colleagues.',
    financeMeaning: 'Financial peace of mind; emotional detachment from greed, allowing resources to circulate naturally.',
    educationMeaning: 'Passionate devotion to humanities, psychology, poetry, and intuitive holistic studies.',
    spiritualMeaning: 'Bhakti and Divine Nectar (Amrita). The pure heart offering its boundless love back to the Divine.',
    advice: 'Open your heart without fear. Let the living waters of compassion overflow into every corner of your life.',
    shadow: 'Emotional codependency expecting someone else to fill a void that only divine connection can satisfy.',
    symbolism: 'The divine hand offering the golden chalice, the white dove of peace descending with the communion host, the lotus pond.',
    element: 'Water',
    astrologicalAssociation: 'Cancer, Scorpio, Pisces (Water Triplicity)',
  },
  {
    id: 'cups_2',
    name: 'Two of Cups',
    number: 2,
    arcana: 'minor',
    suit: 'cups',
    uprightKeywords: ['Mutual Attraction', 'Soul Connection', 'Partnership', 'Reciprocity', 'Harmony'],
    reversedKeywords: ['Imbalance', 'Broken Trust', 'Misunderstanding', 'Codependency', 'Withdrawal'],
    uprightMeaning: 'Two souls exchanging golden chalices under the caduceus of healing; true partnership and mutual respect.',
    reversedMeaning: 'One-sided emotional investment, miscommunication, petty scorekeeping, or drifting apart.',
    loveMeaning: 'Reciprocal romantic union, deep soul communion, harmonious courtship, and respectful mutual vulnerability.',
    careerMeaning: 'Equitable business partnerships, collaborative harmony, productive client relations, and mutual respect.',
    financeMeaning: 'Balanced financial agreements, harmonious shared accounts, and equitable contracts.',
    educationMeaning: 'Productive study partnerships, mutual intellectual support, and cooperative learning.',
    spiritualMeaning: 'The sacred mirror of relationships. Recognizing the Divine reflection in the eyes of another.',
    advice: 'Honor the sacred reciprocity. Give freely and receive with open, humble grace.',
    shadow: 'Losing your individual identity inside the partnership out of desperation to maintain pleasant harmony.',
    symbolism: 'The youth and maiden exchanging cups beneath the winged lion caduceus of Hermes and chimera.',
    element: 'Water',
    astrologicalAssociation: 'Venus in Cancer (1st Decan)',
  },
  {
    id: 'cups_3',
    name: 'Three of Cups',
    number: 3,
    arcana: 'minor',
    suit: 'cups',
    uprightKeywords: ['Celebration', 'Friendship', 'Sisterhood', 'Community Joy', 'Reunion'],
    reversedKeywords: ['Gossip', 'Overindulgence', 'Third Wheel', 'Exclusion', 'Social Fatigue'],
    uprightMeaning: 'Three maidens raising their cups in joyful communion amidst a bountiful harvest; celebrating fellowship.',
    reversedMeaning: 'Toxic peer pressure, malicious gossip, feeling excluded from the inner circle, or social exhaustion.',
    loveMeaning: 'Joyful celebrations, family acceptance of a partner, mutual friends celebrating the couple.',
    careerMeaning: 'Successful project launch party, team celebrations, collaborative camaraderie, and creative milestones.',
    financeMeaning: 'Sharing abundance with friends and family; group crowdfunding or cooperative financial success.',
    educationMeaning: 'Study group triumphs, celebrating graduation, and thriving in collaborative peer workshops.',
    spiritualMeaning: 'Satsanga. Joyous spiritual communion where collective elevated hearts uplift each member.',
    advice: 'Rejoice in the circle of loyal friendship. Share laughter and celebrate the collective harvest.',
    shadow: 'Shallow cliquishness that uses socializing to avoid genuine emotional vulnerability and depth.',
    symbolism: 'Three maidens in flowing robes dancing in a circle holding aloft golden chalices among harvested grapes.',
    element: 'Water',
    astrologicalAssociation: 'Mercury in Cancer (2nd Decan)',
  },
  {
    id: 'cups_4',
    name: 'Four of Cups',
    number: 4,
    arcana: 'minor',
    suit: 'cups',
    uprightKeywords: ['Apathy', 'Contemplation', 'Discontent', 'Missed Opportunity', 'Introspection'],
    reversedKeywords: ['Renewed Interest', 'Awakening', 'Accepting Help', 'Emerging from Slump'],
    uprightMeaning: 'Sitting beneath a tree with folded arms, engrossed in discontent while ignoring the divine cup offered from the cloud.',
    reversedMeaning: 'Shaking off emotional lethargy, noticing the gifts around you, and stepping eagerly back into engagement.',
    loveMeaning: 'Emotional numbness or complacency in a relationship; taking a loving partner for granted.',
    careerMeaning: 'Career boredom, apathy toward routine assignments, or missing an extraordinary promotion due to sulking.',
    financeMeaning: 'Discontent despite adequate resources; comparing your financial lot ungratefully to others.',
    educationMeaning: 'Academic burnout, loss of intellectual motivation, and needing to rekindle original enthusiasm.',
    spiritualMeaning: 'Vairagya born of emotional satiety. The natural turning inward when worldly pleasures fail to satisfy.',
    advice: 'Look up from your brooding. A divine gift is being extended right in front of your eyes; reach out and receive it.',
    shadow: 'Indulging in habitual melancholy and turning self-pity into an aesthetic identity.',
    symbolism: 'The contemplative youth with crossed arms beneath the tree, ignoring the hand emerging from the cloud offering a fourth cup.',
    element: 'Water',
    astrologicalAssociation: 'Moon in Cancer (3rd Decan)',
  },
  {
    id: 'cups_5',
    name: 'Five of Cups',
    number: 5,
    arcana: 'minor',
    suit: 'cups',
    uprightKeywords: ['Grief', 'Regret', 'Loss', 'Mourning the Past', 'Focusing on the Negative'],
    reversedKeywords: ['Acceptance', 'Healing', 'Moving On', 'Forgiveness', 'Seeing the Remaining Cups'],
    uprightMeaning: 'A cloaked figure weeping over three spilled cups, failing to notice the two upright chalices standing behind.',
    reversedMeaning: 'Emerging from grief, turning around to embrace remaining blessings, and forgiving past losses.',
    loveMeaning: 'Grieving a heartbreak, remorse over mistakes made, or mourning the death of a romance.',
    careerMeaning: 'Disappointment over a lost contract or failed venture; needing to salvage remaining assets.',
    financeMeaning: 'Financial losses or bad investments; focusing on what remains intact rather than spilled capital.',
    educationMeaning: 'Disappointment over poor exam marks or rejected applications; learning resilience from setback.',
    spiritualMeaning: 'The crucible of sorrow. Processing grief without identifying forever with the loss.',
    advice: 'Grieve what was lost with dignity, but do not forget to turn around. Two golden cups still stand behind you.',
    shadow: 'Addiction to sorrow; refusing to heal because suffering has become a familiar refuge.',
    symbolism: 'The dark-cloaked mourner with head bowed over three spilled red chalices, with the stone bridge leading to the castle.',
    element: 'Water',
    astrologicalAssociation: 'Mars in Scorpio (1st Decan)',
  },
  {
    id: 'cups_6',
    name: 'Six of Cups',
    number: 6,
    arcana: 'minor',
    suit: 'cups',
    uprightKeywords: ['Nostalgia', 'Innocence', 'Childhood Memories', 'Sweetness', 'Reunion'],
    reversedKeywords: ['Stuck in the Past', 'Rose-Tinted Glasses', 'Outgrown Childhood', 'Unrealistic Nostalgia'],
    uprightMeaning: 'Two children in an old village garden exchanging chalices filled with white flowers; innocence and nostalgic sweetness.',
    reversedMeaning: 'Living in nostalgic memories to escape adult duties, or healing ancient childhood wounds.',
    loveMeaning: 'Childhood sweethearts, reunion with an old flame, or pure, innocent, uncomplicated emotional warmth.',
    careerMeaning: 'Returning to a childhood passion, working with children, or receiving support from an old colleague.',
    financeMeaning: 'Inheritance from family, receiving childhood savings, or support from nostalgic benefactors.',
    educationMeaning: 'Revisiting foundational books, learning with youthful wonder, or elementary educational vocations.',
    spiritualMeaning: 'Returning to original innocence (Sahaja Bhava); recovering the unburdened purity of the soul.',
    advice: 'Embrace the sweet memories of the past to nourish your present, but do not attempt to live yesterday again.',
    shadow: 'Refusing to grow up, retreating into childlike helplessness when adult decisions are required.',
    symbolism: 'The older boy offering a chalice of white blossoms to a younger girl before the peaceful castle courtyard.',
    element: 'Water',
    astrologicalAssociation: 'Sun in Scorpio (2nd Decan)',
  },
  {
    id: 'cups_7',
    name: 'Seven of Cups',
    number: 7,
    arcana: 'minor',
    suit: 'cups',
    uprightKeywords: ['Illusion', 'Multiple Choices', 'Daydreaming', 'Fantasy', 'Wishful Thinking'],
    reversedKeywords: ['Clarity', 'Decisiveness', 'Disillusionment', 'Pragmatic Choice', 'Overcoming Temptation'],
    uprightMeaning: 'A silhouetted seeker gazing at seven cups floating in the clouds, containing dragons, jewels, crowns, and serpents.',
    reversedMeaning: 'Cutting through mental fog, piercing illusions, and making a firm, grounded commitment to reality.',
    loveMeaning: 'Infatuation, romantic idealization, paralysis caused by too many dating options, or fantasy over reality.',
    careerMeaning: 'Overwhelmed by multiple career options; needing to separate viable plans from pipe dreams.',
    financeMeaning: 'Beware get-rich-quick schemes, speculative mirages, and unrealistic financial fantasies.',
    educationMeaning: 'Scattered academic interests; daydreaming instead of mastering the curriculum.',
    spiritualMeaning: 'Maya’s shimmering kaleidoscope. The soul tempted by sensory desires before achieving single-pointed focus.',
    advice: 'Ground your imagination. Make one definitive choice and test its substance in the physical world.',
    shadow: 'Living forever in fantasy to avoid the humble labor of real manifestation.',
    symbolism: 'The seeker seen from behind gazing at seven cloud-borne chalices filled with diverse worldly temptations.',
    element: 'Water',
    astrologicalAssociation: 'Venus in Scorpio (3rd Decan)',
  },
  {
    id: 'cups_8',
    name: 'Eight of Cups',
    number: 8,
    arcana: 'minor',
    suit: 'cups',
    uprightKeywords: ['Walking Away', 'Deeper Purpose', 'Abandoning the Familiar', 'Spiritual Quest', 'Disillusionment'],
    reversedKeywords: ['Fear of Leaving', 'Aimless Wandering', 'Clinging to Dead Ends', 'Returning to the Past'],
    uprightMeaning: 'A cloaked wanderer turns his back on eight neatly stacked golden cups, walking into the mountains under the moon.',
    reversedMeaning: 'Refusing to walk away from an emotionally dead situation, staying out of fear of the cold unknown.',
    loveMeaning: 'Walking away with dignity from a relationship that has run its spiritual course, seeking deeper truth.',
    careerMeaning: 'Resigning from a comfortable but soulless job to embark on an authentic, meaningful career path.',
    financeMeaning: 'Sacrificing material luxury in exchange for inner peace, simplicity, and mental well-being.',
    educationMeaning: 'Abandoning a conventional degree path to pursue an unorthodox spiritual or creative pilgrimage.',
    spiritualMeaning: 'Vairagya and Sannyasa. Walking away from worldly accomplishments in search of the immortal self.',
    advice: 'Have the courage to walk away. When an emotional chapter is complete, lingering only turns wine to vinegar.',
    shadow: 'Chronic escapism; walking away from commitments whenever true emotional intimacy requires effort.',
    symbolism: 'The traveler with his staff walking away from eight cups stacked with an intentional gap, heading toward rugged crags.',
    element: 'Water',
    astrologicalAssociation: 'Saturn in Pisces (1st Decan)',
  },
  {
    id: 'cups_9',
    name: 'Nine of Cups',
    number: 9,
    arcana: 'minor',
    suit: 'cups',
    uprightKeywords: ['Contentment', 'Wish Fulfillment', 'Sensory Pleasure', 'Gratitude', 'Satisfaction'],
    reversedKeywords: ['Smugness', 'Overindulgence', 'Superficial Satisfaction', 'Unfulfilled Wishes'],
    uprightMeaning: 'The prosperous merchant sitting with folded arms and a beaming smile before nine overflowing golden cups; the "Wish Card."',
    reversedMeaning: 'Self-satisfied smugness, gluttony, or achieving worldly desires only to find them spiritually hollow.',
    loveMeaning: 'Deep emotional contentment, mutual adoration, shared pleasure, and romantic wishes fulfilled.',
    careerMeaning: 'Reaching a cherished professional milestone, enjoying professional autonomy, and widespread respect.',
    financeMeaning: 'Bountiful financial comfort, enjoying the fruits of labor, luxurious dining, and secure abundance.',
    educationMeaning: 'Earning a coveted degree, passing examinations with flying colors, and enjoying academic prestige.',
    spiritualMeaning: 'Santosha (Contentment). Resting in deep gratitude for the bountiful blessings of manifest life.',
    advice: 'Enjoy your blessings thoroughly with gratitude, and share your feast with those who are hungry.',
    shadow: 'Smug complacency looking down on others while gorging on sensory pleasure.',
    symbolism: 'The portly merchant in fine blue robes smiling with arms crossed before a curved counter holding nine golden cups.',
    element: 'Water',
    astrologicalAssociation: 'Jupiter in Pisces (2nd Decan)',
  },
  {
    id: 'cups_10',
    name: 'Ten of Cups',
    number: 10,
    arcana: 'minor',
    suit: 'cups',
    uprightKeywords: ['Divine Harmony', 'Family Bliss', 'Emotional Wholeness', 'Peace', 'Enduring Happiness'],
    reversedKeywords: ['Domestic Discord', 'Broken Family', 'Shattered Dreams', 'Struggling for Harmony'],
    uprightMeaning: 'A loving family rejoicing beneath a brilliant rainbow of ten golden cups arching over their idyllic home.',
    reversedMeaning: 'Family dysfunction, pretending harmony for social appearances, or estrangement from relatives.',
    loveMeaning: 'Lifelong marital bliss, deep emotional security, raising a harmonious family, and enduring soul union.',
    careerMeaning: 'An emotionally supportive workplace, work-life balance, and projects that enrich communities.',
    financeMeaning: 'Generational wealth, securing family futures, and financial peace that serves loving relationships.',
    educationMeaning: 'Holistic education that nurtures the whole person; supportive educational communities.',
    spiritualMeaning: 'Ananda and Grihastha Siddhi. The divine kingdom manifest in the humble harmony of loving family life.',
    advice: 'Cherish the love that surrounds you. True wealth is found in the peace and warmth of your home.',
    shadow: 'Demanding perfection from family members, enforcing rigid "happy family" scripts that stifle truth.',
    symbolism: 'The husband and wife with arms entwined and upraised, the dancing children, the rainbow arching with ten cups.',
    element: 'Water',
    astrologicalAssociation: 'Mars in Pisces (3rd Decan)',
  },
  {
    id: 'cups_page',
    name: 'Page of Cups',
    number: 11,
    arcana: 'minor',
    suit: 'cups',
    uprightKeywords: ['Creative Intuition', 'Poetic Heart', 'Surprise Message', 'Gentle Innocence', 'Dreamer'],
    reversedKeywords: ['Emotional Immaturity', 'Escapism', 'Insecurity', 'Whining', 'Fragility'],
    uprightMeaning: 'A sweet youth in floral tunic gazing in wonder at a fish popping up from his golden cup by the singing sea.',
    reversedMeaning: 'Oversensitive tantrums, emotional manipulation, daydreaming to escape responsibilities, or broken promises.',
    loveMeaning: 'Poetic love confessions, sweet romantic notes, tender gestures, and gentle vulnerable courtship.',
    careerMeaning: 'Fresh artistic briefs, creative writing, intuitive problem-solving, and pleasant creative assignments.',
    financeMeaning: 'Intuitive investment instincts; modest funds dedicated to art, poetry, or spiritual pursuits.',
    educationMeaning: 'Gifted in poetry, drama, art, and creative writing; approaching learning with empathetic curiosity.',
    spiritualMeaning: 'The opening of the psychic heart. Receiving unexpected messages from the subtle emotional realms.',
    advice: 'Welcome creative and emotional surprises with wonder. Listen to the intuitive fish speaking from your cup.',
    shadow: 'Fragile victimhood where every constructive criticism is treated as an unbearable emotional attack.',
    symbolism: 'The youth with pink floral tunic gazing at a living fish emerging from his cup against rolling ocean waves.',
    element: 'Water',
    astrologicalAssociation: 'Earth of Water',
  },
  {
    id: 'cups_knight',
    name: 'Knight of Cups',
    number: 12,
    arcana: 'minor',
    suit: 'cups',
    uprightKeywords: ['Romantic Idealist', 'Chivalry', 'Poetic Grace', 'Following the Heart', 'Charm'],
    reversedKeywords: ['Fickle Emotions', 'Disillusionment', 'Manipulation', 'Melodrama', 'Unrealistic Romance'],
    uprightMeaning: 'The noble knight in winged helmet riding his gentle grey steed across the river, offering the golden cup of peace.',
    reversedMeaning: 'Love-bombing followed by ghosting, passive-aggressive brooding, or chasing an unattainable romantic fantasy.',
    loveMeaning: 'Chivalrous courtship, grand romantic gestures, poetry, devotion, and following heart-centered passion.',
    careerMeaning: 'Diplomacy, mediation, artistic vocations, counseling, and promoting harmony in workplace relations.',
    financeMeaning: 'Financing creative passions, ethical investments, and avoiding cutthroat financial practices.',
    educationMeaning: 'Mastering literature, art history, classical poetry, and compassionate interpersonal counseling.',
    spiritualMeaning: 'The Quest for the Holy Grail. The romantic pilgrim seeking the supreme chalice of divine love.',
    advice: 'Follow your heart’s noble inspiration, but ensure your horse keeps its hooves grounded in practical reality.',
    shadow: 'Falling in love with the idea of love rather than the real, imperfect human being standing before you.',
    symbolism: 'The knight wearing fish-scaled armor with winged helmet and boots, holding his cup with reverent care.',
    element: 'Water',
    astrologicalAssociation: 'Air of Water',
  },
  {
    id: 'cups_queen',
    name: 'Queen of Cups',
    number: 13,
    arcana: 'minor',
    suit: 'cups',
    uprightKeywords: ['Empathetic Healer', 'Emotional Depth', 'Intuitive Wisdom', 'Compassion', 'Grace'],
    reversedKeywords: ['Codependency', 'Emotional Manipulation', 'Martyrdom', 'Smothering', 'Moodiness'],
    uprightMeaning: 'The serene queen seated on her sea-carved throne, contemplating an ornate closed chalice with profound empathy.',
    reversedMeaning: 'Emotional overwhelm, projective moodiness, smothering codependency, or playing the wounded martyr.',
    loveMeaning: 'Unconditional emotional refuge, deep empathic listening, soulful intimacy, and unwavering romantic devotion.',
    careerMeaning: 'Psychotherapy, nursing, intuitive counseling, spiritual caregiving, and fostering psychological safety at work.',
    financeMeaning: 'Intuitive money management; generosity balanced with careful protection of family nest eggs.',
    educationMeaning: 'Exceptional emotional intelligence, mastery of psychoanalysis, clinical psychology, and contemplative arts.',
    spiritualMeaning: 'The Divine Mother’s ocean of mercy (Karuna Sagara). Holding space for all suffering without drowning.',
    advice: 'Trust your profound intuitive sensitivity. Anchor your emotional depth in compassionate stillness.',
    shadow: 'Absorbing everyone else’s emotional trauma until your own vessel becomes toxic and depleted.',
    symbolism: 'The queen seated on a throne decorated with mermaids and cherubs, holding an ornate church-like closed chalice.',
    element: 'Water',
    astrologicalAssociation: 'Water of Water',
  },
  {
    id: 'cups_king',
    name: 'King of Cups',
    number: 14,
    arcana: 'minor',
    suit: 'cups',
    uprightKeywords: ['Emotional Mastery', 'Compassionate Leader', 'Poise Under Pressure', 'Diplomacy', 'Wisdom'],
    reversedKeywords: ['Emotional Volatility', 'Cold Manipulation', 'Repression', 'Passive Aggression', 'Addiction'],
    uprightMeaning: 'The king seated upon a floating stone throne amidst turbulent seas, commanding storms with calm emotional mastery.',
    reversedMeaning: 'Suppressed rage erupting unpredictably, manipulative guilt-tripping, or emotional withdrawal behind a fortress.',
    loveMeaning: 'Emotionally mature, calm, protective partner who provides unwavering emotional stability through all life storms.',
    careerMeaning: 'Wise executive diplomacy, chief negotiator, counseling leadership, and staying tranquil during crises.',
    financeMeaning: 'Calm, balanced financial leadership; never panicked by market fluctuations or emotional speculation.',
    educationMeaning: 'Distinguished professorship in psychology, ethics, diplomacy, and mentorship of emerging scholars.',
    spiritualMeaning: 'The Sthitaprajna (Sage of Steady Wisdom). The one who navigates the ocean of Samsara without being rocked by waves.',
    advice: 'Command your emotional ocean. Master your feelings through wisdom and respond to turmoil with steady compassion.',
    shadow: 'Using your understanding of other people’s emotional vulnerabilities to subtly manipulate them.',
    symbolism: 'The king on his throne floating upon the churning ocean, wearing a fish amulet and holding his sceptre with tranquility.',
    element: 'Water',
    astrologicalAssociation: 'Fire of Water',
  },
];
