import { TarotCard } from '../types';

export const MINOR_PENTACLES: TarotCard[] = [
  {
    id: 'pentacles_1_ace',
    name: 'Ace of Pentacles',
    number: 1,
    arcana: 'minor',
    suit: 'pentacles',
    uprightKeywords: ['Material Opportunity', 'Financial Seed', 'Abundance', 'Tangible Manifestation', 'Prosperity'],
    reversedKeywords: ['Missed Investment', 'Financial Insecurity', 'Greed', 'Poor Planning', 'Delayed Returns'],
    uprightMeaning: 'The divine hand offering a golden pentacle hovering over an archway of flowering lilies leading to lush mountains.',
    reversedMeaning: 'Frittering away a golden financial opportunity, poor resource allocation, or greed blinding you to real value.',
    loveMeaning: 'Grounded, stable, deeply committed relationship foundation; sharing tangible security, home, and mutual care.',
    careerMeaning: 'A lucrative new job offer, launching a profitable business, receiving venture capital, and tangible career rewards.',
    financeMeaning: 'The golden seed of wealth; purchasing real estate, starting an investment portfolio, and solid financial security.',
    educationMeaning: 'Full scholarship grant, practical vocational training, and mastering tangible, marketable professional skills.',
    spiritualMeaning: 'Prithvi and Lakshmi. The divine realizing itself through the sacred, beautiful reality of the material earth.',
    advice: 'Plant this golden seed in rich soil. Cultivate it with daily practical care and watch it grow into enduring wealth.',
    shadow: 'Obsessing over material accumulation until money ceases to be a tool and becomes a false idol.',
    symbolism: 'The divine hand holding a large gold coin inscribed with a pentagram, the rose garden, the floral archway to mountain peaks.',
    element: 'Earth',
    astrologicalAssociation: 'Taurus, Virgo, Capricorn (Earth Triplicity)',
  },
  {
    id: 'pentacles_2',
    name: 'Two of Pentacles',
    number: 2,
    arcana: 'minor',
    suit: 'pentacles',
    uprightKeywords: ['Balance', 'Adaptability', 'Juggling Priorities', 'Resource Flow', 'Flexibility'],
    reversedKeywords: ['Overwhelmed', 'Financial Chaos', 'Dropping the Ball', 'Disorganization', 'Overextended'],
    uprightMeaning: 'A nimble dancer juggling two golden pentacles linked by an infinity loop, balancing life’s demands against rolling waves.',
    reversedMeaning: 'Overcommitted schedule, bouncing checks, dropping crucial responsibilities, and financial chaos.',
    loveMeaning: 'Balancing relationship time with heavy work demands; needing flexibility and lighthearted playfulness.',
    careerMeaning: 'Multi-tasking across several demanding projects, agile pivoting, and adapting smoothly to shifting markets.',
    financeMeaning: 'Juggling cash flow, managing multiple revenue streams, and balancing income against periodic expenses.',
    educationMeaning: 'Balancing work and study, managing multiple academic assignments simultaneously with agile time-management.',
    spiritualMeaning: 'The sacred play of Lila. Dancing lightly upon the turbulent waves of circumstance without falling.',
    advice: 'Stay light on your feet. Maintain flexible balance and treat your shifting obligations as a graceful dance.',
    shadow: 'Spreading yourself so thin across twenty trivial tasks that you never complete a single masterpiece.',
    symbolism: 'The youth in dancing costume balancing two pentacles enclosed in a green lemniscate, ships riding undulating waves.',
    element: 'Earth',
    astrologicalAssociation: 'Jupiter in Capricorn (1st Decan)',
  },
  {
    id: 'pentacles_3',
    name: 'Three of Pentacles',
    number: 3,
    arcana: 'minor',
    suit: 'pentacles',
    uprightKeywords: ['Teamwork', 'Craftsmanship', 'Collaboration', 'Mastery', 'Building Foundations'],
    reversedKeywords: ['Lack of Teamwork', 'Shoddy Work', 'Ego Friction', 'Misaligned Goals', 'Unskilled Labor'],
    uprightMeaning: 'A skilled stonemason consulting with an architect and monk in a cathedral; collaborative mastery and fine craftsmanship.',
    reversedMeaning: 'Petty workplace friction, shoddy cutting of corners, refusal to collaborate, and disregard for standards.',
    loveMeaning: 'Building a shared life together as a harmonious team, seeking wise relationship counseling, and mutual respect.',
    careerMeaning: 'Successful cross-functional teamwork, professional recognition of technical craftsmanship, and architectural building.',
    financeMeaning: 'Investing in skilled trades, hiring expert financial architects, and building enduring infrastructural wealth.',
    educationMeaning: 'Peer collaborative research, working closely with academic advisors, and mastering technical trades.',
    spiritualMeaning: 'The building of the inner temple. Aligning body, mind, and soul through cooperative, disciplined Sadhana.',
    advice: 'Collaborate with skilled specialists. Value every contributor’s role and build with patient, exacting craftsmanship.',
    shadow: 'Professional snobbery that devalues the essential contribution of hands-on laborers or mentors.',
    symbolism: 'The stonemason on his bench holding chisel and mallet, consulting two cloaked elders beneath the cathedral arch.',
    element: 'Earth',
    astrologicalAssociation: 'Mars in Capricorn (2nd Decan)',
  },
  {
    id: 'pentacles_4',
    name: 'Four of Pentacles',
    number: 4,
    arcana: 'minor',
    suit: 'pentacles',
    uprightKeywords: ['Financial Security', 'Conservation', 'Frugality', 'Control', 'Protecting Assets'],
    reversedKeywords: ['Greed', 'Miserliness', 'Fear of Poverty', 'Reckless Spending', 'Possessiveness'],
    uprightMeaning: 'A crowned figure seated before a city clutching a pentacle to his chest, one under each foot and one on his crown; guarding wealth.',
    reversedMeaning: 'Pathological hoarding, paralyzing fear of poverty, or swinging to the opposite extreme of reckless spending.',
    loveMeaning: 'Emotional stinginess, possessiveness, suffocating a partner out of fear of loss, or withholding affection.',
    careerMeaning: 'Clinging tightly to job security, protecting intellectual property, and resisting organizational changes.',
    financeMeaning: 'Tight budget control, building an emergency savings reserve, and conservative asset preservation.',
    educationMeaning: 'Hoarding study materials, refusing to share notes with classmates, and guarding research findings.',
    spiritualMeaning: 'Kripana (The Miser). Clinging tightly to material identification, forgetting that everything belongs to the Divine.',
    advice: 'Protect your legitimate security, but remember that closed fists cannot receive new blessings. Loosen your grip.',
    shadow: 'Allowing the terror of poverty to turn your heart into cold, unyielding stone.',
    symbolism: 'The crowned figure seated firmly holding a pentacle with both arms, resting both feet on pentacles, with the city behind.',
    element: 'Earth',
    astrologicalAssociation: 'Sun in Capricorn (3rd Decan)',
  },
  {
    id: 'pentacles_5',
    name: 'Five of Pentacles',
    number: 5,
    arcana: 'minor',
    suit: 'pentacles',
    uprightKeywords: ['Hardship', 'Poverty', 'Feeling Left in the Cold', 'Isolation', 'Material Struggle'],
    reversedKeywords: ['Recovery', 'Finding Warmth', 'End of Hardship', 'Accepting Help', 'Renewed Security'],
    uprightMeaning: 'Two impoverished figures trudging through driving snow past the glowing stained-glass window of a warm sanctuary.',
    reversedMeaning: 'Finding employment after long drought, opening the door to sanctuary, and recovering from illness or poverty.',
    loveMeaning: 'Feeling emotionally rejected or isolated; weathering severe financial strain together as a couple.',
    careerMeaning: 'Job loss, corporate layoffs, career rejection, or feeling like an unwanted outsider in your industry.',
    financeMeaning: 'Acute financial stress, mounting debt, medical expenses, and needing to reach out for assistance.',
    educationMeaning: 'Losing a scholarship, academic struggles, and feeling isolated from the campus community.',
    spiritualMeaning: 'The test of adversity. Discovering that when external wealth is stripped away, the inner light remains untouched.',
    advice: 'Look up from the snow. The sanctuary window is glowing with warmth; knock on the door and ask for help.',
    shadow: 'Prideful stubbornness that freezes in the cold rather than humbling oneself to seek assistance.',
    symbolism: 'The crippled mendicant on crutches and the shivering beggar passing beneath the glowing church window with five pentacles.',
    element: 'Earth',
    astrologicalAssociation: 'Mercury in Taurus (1st Decan)',
  },
  {
    id: 'pentacles_6',
    name: 'Six of Pentacles',
    number: 6,
    arcana: 'minor',
    suit: 'pentacles',
    uprightKeywords: ['Generosity', 'Charity', 'Fair Distribution', 'Reciprocal Support', 'Philanthropy'],
    reversedKeywords: ['Strings Attached', 'Abuse of Power', 'Debts Unpaid', 'One-Sided Generosity', 'Scams'],
    uprightMeaning: 'A prosperous merchant holding the scales of justice while gently dropping golden coins into the hands of grateful mendicants.',
    reversedMeaning: 'Conditional charity with hidden strings attached, condescending superiority, or being taken advantage of financially.',
    loveMeaning: 'Healthy emotional reciprocity, mutual generosity, and sharing time, affection, and resources without scorekeeping.',
    careerMeaning: 'Receiving mentorship, venture funding, performance bonuses, or fair compensation for hard work.',
    financeMeaning: 'Charitable donations, philanthropic endowments, receiving loan approvals, and fair distribution of wealth.',
    educationMeaning: 'Academic grants, research fellowships, and generous mentorship from senior faculty members.',
    spiritualMeaning: 'Dana and Seva. Giving freely with humility, recognizing that the giver, the gift, and the receiver are one.',
    advice: 'Give generously where you are endowed with plenty, and receive with gracious humility where you are in need.',
    shadow: 'Giving only to control the recipient, cultivating dependency to feed a philanthropic savior complex.',
    symbolism: 'The merchant in fine robes weighing the scales in his left hand while distributing coins with his right to two kneeling figures.',
    element: 'Earth',
    astrologicalAssociation: 'Moon in Taurus (2nd Decan)',
  },
  {
    id: 'pentacles_7',
    name: 'Seven of Pentacles',
    number: 7,
    arcana: 'minor',
    suit: 'pentacles',
    uprightKeywords: ['Patience', 'Long-Term Investment', 'Evaluation', 'Sustainable Growth', 'Harvest Pending'],
    reversedKeywords: ['Impatience', 'Poor ROI', 'Wasted Effort', 'Giving Up Too Early', 'Neglect'],
    uprightMeaning: 'A farmer leaning upon his spade, contemplating the seven golden pentacles ripening on the vine; patient stewardship.',
    reversedMeaning: 'Frustration with slow growth, throwing good money after bad, or abandoning a crop right before the harvest.',
    loveMeaning: 'Evaluating the long-term viability of a relationship; knowing that deep love requires years of steady cultivation.',
    careerMeaning: 'Assessing long-term career progression, reviewing milestones, and patiently waiting for strategic investments to mature.',
    financeMeaning: 'Compound interest, long-term retirement accounts, real estate appreciation, and resisting hasty trading.',
    educationMeaning: 'Patiently grinding through years of doctoral or medical study, knowing the harvest will arrive in due season.',
    spiritualMeaning: 'Karmaphala and patience. Doing the righteous work (Karma) without anxious attachment to the immediate fruit.',
    advice: 'Be patient. You have planted the right seeds and watered the soil; let nature and time do their essential work.',
    shadow: 'Endless passive waiting without taking necessary weeding and pruning actions to ensure harvest health.',
    symbolism: 'The young laborer leaning on his hoe, gazing thoughtfully at seven golden pentacles hanging upon a lush green bush.',
    element: 'Earth',
    astrologicalAssociation: 'Saturn in Taurus (3rd Decan)',
  },
  {
    id: 'pentacles_8',
    name: 'Eight of Pentacles',
    number: 8,
    arcana: 'minor',
    suit: 'pentacles',
    uprightKeywords: ['Apprenticeship', 'Repetitive Mastery', 'Craftsmanship', 'Dedication', 'Detail-Oriented'],
    reversedKeywords: ['Perfectionism', 'Lack of Ambition', 'Careless Work', 'Burnout', 'Tedium'],
    uprightMeaning: 'The artisan in his workshop carving intricate designs into golden pentacles one by one; dedicated mastery of craft.',
    reversedMeaning: 'Careless, sloppy workmanship, cutting corners, or becoming trapped in soul-crushing repetitive drudgery.',
    loveMeaning: 'Putting in the daily, humble, unglamorous effort required to build a healthy, enduring, trustworthy relationship.',
    careerMeaning: 'Upskilling, mastering technical tools, deliberate practice, meticulous quality control, and professional dedication.',
    financeMeaning: 'Steady, reliable income earned through skilled trade; reinvesting profits into better tools and training.',
    educationMeaning: 'Rigorous study habits, coding daily, mastering grammar or mathematics through disciplined problem sets.',
    spiritualMeaning: 'Abhyasa (Sustained Practice). The humble, repetitive daily discipline that transforms raw mind into spiritual gold.',
    advice: 'Focus on the craft itself. Hone your technique with patient repetition; true mastery is built one stroke at a time.',
    shadow: 'Narrow tunnel vision, obsessing over minor technical details while ignoring the broader purpose of the work.',
    symbolism: 'The craftsman seated at his bench carving a pentacle with hammer and chisel, six finished coins mounted on the post.',
    element: 'Earth',
    astrologicalAssociation: 'Sun in Virgo (1st Decan)',
  },
  {
    id: 'pentacles_9',
    name: 'Nine of Pentacles',
    number: 9,
    arcana: 'minor',
    suit: 'pentacles',
    uprightKeywords: ['Self-Sufficiency', 'Luxury', 'Refined Abundance', 'Solitary Grace', 'Financial Independence'],
    reversedKeywords: ['Over-spending', 'Living Beyond Means', 'Superficial Vanity', 'Loneliness in Luxury'],
    uprightMeaning: 'An elegant woman in a flowing silk robe walking through her bountiful vineyard with a hooded falcon; graceful independence.',
    reversedMeaning: 'Living on credit to project false luxury, financial dependence on others, or loneliness amidst material wealth.',
    loveMeaning: 'Complete self-worth that does not need a partner to feel whole; attracting a mate from sovereignty rather than need.',
    careerMeaning: 'Reaching a prestigious pinnacle of independent consulting, executive autonomy, and enjoying the fruits of labor.',
    financeMeaning: 'Financial independence, luxurious personal assets, beautiful real estate, and sophisticated taste.',
    educationMeaning: 'Publishing major independent research, enjoying intellectual autonomy, and scholarly distinction.',
    spiritualMeaning: 'The soul resting in dignified self-sufficiency (Atmarama), enjoying creation without being entangled by it.',
    advice: 'Savor your hard-earned self-reliance. You have cultivated this garden with your own hands; enjoy its beauty.',
    shadow: 'Aloof snobbery that looks down on those still struggling in the marketplace, isolating yourself in luxury.',
    symbolism: 'The noblewoman in yellow robe embroidered with flowers, a hooded hunting falcon on her gloved hand amidst heavy grapevines.',
    element: 'Earth',
    astrologicalAssociation: 'Venus in Virgo (2nd Decan)',
  },
  {
    id: 'pentacles_10',
    name: 'Ten of Pentacles',
    number: 10,
    arcana: 'minor',
    suit: 'pentacles',
    uprightKeywords: ['Generational Wealth', 'Legacy', 'Family Dynasty', 'Long-Term Security', 'Tradition'],
    reversedKeywords: ['Family Feuds', 'Disputed Inheritance', 'Financial Collapse', 'Rigid Tradition', 'Loss of Legacy'],
    uprightMeaning: 'Three generations and their loyal hounds gathered beneath an arched manor gate adorned with ten golden pentacles.',
    reversedMeaning: 'Bitter disputes over wills and inheritances, financial ruin of family businesses, or suffocating family pressure.',
    loveMeaning: 'Deep, generational commitment, blending families harmoniously, and building an enduring dynasty together.',
    careerMeaning: 'Building a multi-generational enterprise, establishing an enduring foundation, and institutional permanence.',
    financeMeaning: 'Family trusts, estate planning, generational real estate, and permanent financial security.',
    educationMeaning: 'Endowed academic chairs, classical lineage learning, and passing knowledge to future generations.',
    spiritualMeaning: 'Pitri-Kula blessing. The ancestral lineage harmonized and honored, anchoring spiritual realization in material continuity.',
    advice: 'Think in terms of generations, not quarters. Build what will outlive you and nourish those who come after.',
    shadow: 'Valuing ancestral money and family pedigree above the living souls of your own children.',
    symbolism: 'The patriarch in embroidered robe petting his dogs, the couple talking under the arch, the child, ten pentacles in Tree of Life pattern.',
    element: 'Earth',
    astrologicalAssociation: 'Mercury in Virgo (3rd Decan)',
  },
  {
    id: 'pentacles_page',
    name: 'Page of Pentacles',
    number: 11,
    arcana: 'minor',
    suit: 'pentacles',
    uprightKeywords: ['Studious Scholar', 'Practical Curiosity', 'Financial Opportunity', 'Ambition', 'Diligence'],
    reversedKeywords: ['Procrastination', 'Lack of Follow-Through', 'Shortsightedness', 'Careless Errors'],
    uprightMeaning: 'A focused youth standing in a blooming meadow gazing with rapt attention at a golden pentacle resting in his hands.',
    reversedMeaning: 'Lazy procrastination, daydreaming about wealth without doing homework, or dropping out due to lack of discipline.',
    loveMeaning: 'Dependable, humble, loyal courtship; building affection through practical acts of service and dependability.',
    careerMeaning: 'Internships, learning foundational business operations, taking certification courses, and diligent execution.',
    financeMeaning: 'A promising financial proposal or junior investment; beginning a savings plan with disciplined intent.',
    educationMeaning: 'A dedicated, studious student, meticulous note-taking, and excelling through steady preparation.',
    spiritualMeaning: 'The humble sadhaka grounding lofty spiritual theories into daily bodily routines and ethical conduct.',
    advice: 'Adopt a humble, studious attitude. Study the practical principles and build your foundation step by step.',
    shadow: 'Becoming a perpetual student who collects certifications to avoid the vulnerability of real-world execution.',
    symbolism: 'The youth in green and red tunic gazing intently at the gold coin balanced on his fingertips in a fertile field.',
    element: 'Earth',
    astrologicalAssociation: 'Earth of Earth',
  },
  {
    id: 'pentacles_knight',
    name: 'Knight of Pentacles',
    number: 12,
    arcana: 'minor',
    suit: 'pentacles',
    uprightKeywords: ['Methodical Worker', 'Unwavering Duty', 'Reliability', 'Patience', 'Routine Mastery'],
    reversedKeywords: ['Stubborn Sluggishness', 'Workaholism', 'Boring Monotony', 'Resistance to Change'],
    uprightMeaning: 'The heavily armored knight mounted on a sturdy plough horse amidst plowed fields, holding his gold pentacle with steady duty.',
    reversedMeaning: 'Exhausting routine, refusing to innovate, obstinate stubbornness, or sacrificing relationships to workaholism.',
    loveMeaning: 'The most loyal, dependable, faithful romantic partner imaginable; slow to move, but steadfast forever.',
    careerMeaning: 'Operations manager, chief compliance officer, meticulous project execution, and delivering on every promise.',
    financeMeaning: 'Consistent conservative wealth building; never seduced by fads, compounding wealth steadily over decades.',
    educationMeaning: 'Meticulous academic discipline, exhaustive literature review, and completing difficult dissertations through sheer grit.',
    spiritualMeaning: 'Karma Yoga in its purest form. Serving the Divine through relentless, unglamorous, dedicated daily duty.',
    advice: 'Keep plowing the field with steady patience. Methodical consistency will outpace flash and haste every single time.',
    shadow: 'Inflexible stubbornness that refuses to adapt even when the field has turned into desert sand.',
    symbolism: 'The knight on a heavy black draft horse standing motionless in a plowed field, holding a single golden coin.',
    element: 'Earth',
    astrologicalAssociation: 'Air of Earth',
  },
  {
    id: 'pentacles_queen',
    name: 'Queen of Pentacles',
    number: 13,
    arcana: 'minor',
    suit: 'pentacles',
    uprightKeywords: ['Nurturing Abundance', 'Practical Care', 'Down-to-Earth Grace', 'Homemaker', 'Financial Wisdom'],
    reversedKeywords: ['Smothering Care', 'Material Insecurity', 'Neglecting Self', 'Work-Life Imbalance'],
    uprightMeaning: 'The gracious queen seated on a carved throne surrounded by roses and lush wildlife, cradling a golden pentacle on her lap.',
    reversedMeaning: 'Worrying obsessively about finances, neglecting self-care to feed others, or smothering family with material control.',
    loveMeaning: 'Warm, deeply grounded, nurturing partner who creates a sanctuary of comfort, delicious food, and sensual ease.',
    careerMeaning: 'Pragmatic business leadership, managing budgets with maternal wisdom, and fostering a supportive workplace culture.',
    financeMeaning: 'Sound financial management, investing in organic food, home improvement, and tangible long-term assets.',
    educationMeaning: 'Practical applied learning; connecting academic theory directly to environmental and human well-being.',
    spiritualMeaning: 'Annapurna (Goddess of Nourishment). Sanctifying the physical world and seeing the Divine in the bread and hearth.',
    advice: 'Ground yourself in practical care. Tend to your physical body, your home, and your loved ones with warm abundance.',
    shadow: 'Measuring human worth exclusively by bank accounts, manicured lawns, and material respectability.',
    symbolism: 'The queen seated on a throne carved with goats, cherubs, and fruit, holding a pentacle with a rabbit bounding by her feet.',
    element: 'Earth',
    astrologicalAssociation: 'Water of Earth',
  },
  {
    id: 'pentacles_king',
    name: 'King of Pentacles',
    number: 14,
    arcana: 'minor',
    suit: 'pentacles',
    uprightKeywords: ['Financial Emperor', 'Abundance Master', 'Security', 'Enterprise', 'Generous Patron'],
    reversedKeywords: ['Greedy Miser', 'Corrupt Tycoon', 'Materialistic Snob', 'Financial Bankruptcy'],
    uprightMeaning: 'The sovereign master of wealth seated upon his vine-adorned throne with bulls carved in stone, holding his golden pentacle with calm authority.',
    reversedMeaning: 'Ruthless corporate exploitation, corrupt financial dealings, or putting a price tag on human relationships.',
    loveMeaning: 'Devoted, generous, deeply stable partner who provides luxurious security and steadfast emotional support.',
    careerMeaning: 'Successful industrialist, seasoned chief financial officer, master builder, and respected pillar of industry.',
    financeMeaning: 'Bountiful wealth mastery, substantial asset holdings, philanthropic endowments, and enduring solvency.',
    educationMeaning: 'Endowing universities, establishing business schools, and applying commercial wisdom to practical governance.',
    spiritualMeaning: 'Kubera and the righteous Grihastha. Holding vast material resources with complete inner detachment and generosity.',
    advice: 'Manage your enterprise with steadfast wisdom. Build tangible value that provides security and shelter for many.',
    shadow: 'Believing that everything and everyone can be bought, reduced to a transaction on a spreadsheet.',
    symbolism: 'The crowned king in robes adorned with bunches of grapes, resting his foot on an armored bull carving, holding a golden coin and sceptre.',
    element: 'Earth',
    astrologicalAssociation: 'Fire of Earth',
  },
];
